### ISSUE TITLE
How to toggle dark theme

### ISSUE THREAD

**Issue by hegzploit** [Jieiku/abridge#10]
The preview image for the theme seems to show a dark theme, my phone also does render the dark theme but I can't find anything in the readme about that.

**Comment by Jieiku** [comment]
The theme is either light or dark depending on browser/system preference.

In your browser settings you will find theme and color settings, even on android google chrome, if you open the settings you will find a Setting for Theme, depending on how you set this the appropriate theme is displayed automatically.

What makes this possible is the section in the the `abridge/sass/themes/_auto.scss`

`@media (prefers-color-scheme: dark) {`

**Comment by hegzploit** [comment]
> The theme is either light or dark depending on browser/system preference.
> 
> In your browser settings you will find theme and color settings, even on android google chrome, if you open the settings you will find a Setting for Theme, depending on how you set this the appropriate theme is displayed automatically.
> 
> What makes this possible is the section in the the `abridge/sass/themes/_auto.scss`
> 
> `@media (prefers-color-scheme: dark) {`
> 
> I also included the base light and dark themes, so if you wanted you could force one or the other (For everyone). You would modify: `abridge/sass/abridge.scss`
> 
> ```
> @import "themes/auto";
> //@import "themes/dark";
> //@import "themes/light";
> ```
> 
> notice above dark and light are commented out, but you could comment out auto and import just dark or light if you wanted.
> 
> If you modify which one you import you will need to rebuild your site, (zola build or zola serve) as this is when the scss is compiled to css
> 
> It is actually possible to use javascript and also have all themes downloaded and be user selectable, but it increases the overall page load size because of the extra css and javascript, which is not the goal of abridge. You can however see such functionality in some of the other themes that have user selectable themes.
> 
> For example the AdiDoks theme has user selectable theme (click the moon/sun icon in top right) https://adidoks.netlify.app/
> 
> I wont be adding such functionality to abridge though because of the larger page load size. (unless there is a way to add it as disabled by default, no time to think about it now.)
> 
> I think its best to just use auto, dark or light depending on your site design and target audience.

Awesome, I didn't know that auto theme was a thing.

I think I will leave it as is for now, the default light theme Is great but the orange lacks contrast with the white background imo.

I respect the No-JS approach and I think it's really worth it to have themes work that way.

Something a bit off-topic but I've spent the last 2 hours fighting with the paginator to get it to work until I found out about the requirement of the "more" block in order for it to build succesfully, also `math = true` doesn't seem to work for some reason not sure why.

Loving the theme so far, really fast and lightweight. props.

**Comment by Jieiku** [comment]
yeah, I will plan to tweak the contrast a bit more, totally agree.

**Comment by Jieiku** [comment]
I adjusted the contrast for the light theme, I also added the default Zola search box, it is the only javascript used in the site and if you set `build_search_index = false` then the search box will be hidden and the extra js files will not be loaded.

**Comment by hegzploit** [comment]
> I adjusted the contrast for the light theme, I also added the default Zola search box, it is the only javascript used in the theme and if you set `build_search_index = false` then the search box and the extra js files will not be loaded.

Awesome work, I'll pull the new version once I'm home.
KaTeX isn't a priority for me right now but I did set it on my old theme by including a single js file in the base header, I wouldn't do that here though since It defeats the minimal JS style.

**Comment by Jieiku** [comment]
AH YES! I noticed that when I first started as well.

I will investigate the `<!--more--!>` and see if I can add a check, if not I will add a note about it to the readme.

**Comment by Jieiku** [comment]
I fixed the issue with not compiling when `<!--more--!>` is missing. 

I also added katex support.

If you think of anything else feel free to open another issue, thanks again.

**Comment by Jieiku** [comment]
Just to let you know, I fixed the math shortcode and autoload:

https://jieiku.github.io/abridge-demo/overview-math/

**Comment by Jieiku** [comment]
Make sure to review the config.toml, likely a LOT of new values for you to implement. (I have been very busy!)

**Comment by Jieiku** [comment]
There is now a Dark/Light Toggle Feature: https://github.com/Jieiku/abridge/commit/a987f5ae821ddf45eabda034fa7991a327d5d219

You can see it in the demo: https://abridge.netlify.app/

LOTS of changes, make sure to review config.toml

**Comment by Jieiku** [comment]
I further optimized the theme switcher, it is now the first loaded file in the head, this eliminates the tiny bit of background color flash that you sometimes see between page clicks.

https://github.com/Jieiku/abridge/commit/bf285d369ef883eaffe883f2058fa470062638fb

**Comment by simbleau** [comment]
Looks awesome! 

Only 2 minor things
- header links aren't centered
- search box has 2 search icons

![image](https://user-images.githubusercontent.com/48108917/172921123-27532d6e-74a7-4988-833c-3128fc993ed0.png)

**Comment by Jieiku** [comment]
I have no idea how you got a second search icon, I think that might be a style applied by android devices to any search field, is it actually clickable?

**Comment by Jieiku** [comment]
Bah, I just noticed another issue, prioritizing the the theme.js in the head causes a font flicker instead on page load. I think I have found a good solution and will try implementing it now, stand by.

**Comment by Jieiku** [comment]
I further Optimized the Theme Switcher. Also I created a bundle js for the katex js files, so now there are not so many of them. (only 1 css file and 1 js file for katex)

**Comment by hegzploit** [comment]
> Yeah, I have been trying my best to make most of the configuration through the config.toml
> 
> If I simply change something the way that I want it, then other people will open an issue report wanting it a different way, configuration allows people to set things however they want it.
> 
> I think last night I just hit maintenance status on this Theme, my todo list is now very tiny!
> 
> One thing I will be knocking out today is a copy code block to clipboard feature.

This is really handy and makes this theme even more complete, now I might be getting ahead of myself here but, have you thought of an analytics solution to use with zola/abridge.

**Comment by Jieiku** [comment]
I use matomo, it can be made to work with a simple js include or if you self host or have shell access at your host you an process the nginx server logs directly.

`https://github.com/matomo-org/matomo-log-analytics`

**Comment by Jieiku** [comment]
What I am actually planning to implement next is a comments system, so far I have found [schnack](https://github.com/schn4ck/schnack) but I am not certain it is what I want to use, still searching for options and comparing.

**Comment by hegzploit** [comment]
I will be looking into other solutions, I don't mind self hosting everything tbh, will look into it once I'm free.

as for the comments, I've found [Utterances](https://utteranc.es/) which is based off GitHub issues. 
check [this blog](https://www.heinrichhartmann.com/) that uses that solution.

I'm not 100% happy with it as I would prefer something independent but who doesn't have GitHub these days anyway.

**Comment by Jieiku** [comment]
I think thats probably perfect, will probably try out Utterances myself.

**Comment by Jieiku** [comment]
I found [Uncomment](https://github.com/nielssp/uncomment) and I am planning to use it, it is very young but I really like that being lightweight is a focus of the project.

**Comment by simbleau** [comment]
Please make it a toggle! :)

**Comment by hegzploit** [comment]
> Please make it a toggle! :)

It is a toggle, you have to visit your `config.toml` configure it. you can even copy [this](https://github.com/Jieiku/abridge/blob/master/config.toml) template and edit it to your needs, make sure you're on the latest version of Abridge though.

**Comment by hegzploit** [comment]
> I found [Uncomment](https://github.com/nielssp/uncomment) and I am planning to use it, it is very young but I really like that being lightweight is a focus of the project. (I am the second person to star it, this project needs more attention, it looks awesome!)

Looks awesome, I've seen his blog where he uses It and seems cool, bonus points for using rust too haha.
