### ISSUE TITLE
How to override favicons and logo?

### ISSUE THREAD

**Issue by jalemann** [Jieiku/abridge#106]
How do I override the favicons and logo?
I thought it would automatically use favicons if they are provided in the base `static` dir if they have the same name as those in the `themes/abridge/static` dir, but that doesn't seem to work?

Is there a way to set this in the `config.toml` or do it any other way than replace the files in the `themes` dir? I would want to avoid this as this makes it more annoying to update the themes git submodule.

**Comment by jalemann** [comment]
Nvm I made a mistake by mixing up the `static` and `content/static` directories. It does override if files are in the `static` dir.

**Comment by Jieiku** [comment]
yep, you can override the files directly, you can also disable some of them in the config.toml file if  you comment them out:

favicon_theme_color = "#333333"
favicon_ms_color = "#333333"
favicon_webmanifest = "site.webmanifest" # Used for android-chrome-512x512.png and android-chrome-192x192.png
#favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
#favicon_mask_color = "#ff9900"
#favicon180 = "apple-touch-icon.png" # apple-touch-icon.png
#favicon32 = "favicon-32x32.png" # favicon-32x32.png
favicon16 = "favicon-16x16.png" # favicon-16x16.png

**Comment by samueloph** [comment]
Adding the icons to the `static` in the root of the project doesn't work and neither adding them to `content/static`.

I'm assuming the only way is to override the files at `themes/abridge/static/`? But this would mean we can't use the theme as a git submodule, since we have to override the file within the submodule.

Is this correct?

**Comment by Jieiku** [comment]
Can also exclude them:

add this to your config.toml:

```toml
ignored_static = ["apple-touch-icon.png","banner.png","safari-pinned-tab.svg","favicon*","m*.png","android-chrome*png"]
```

found the answer here: https://www.getzola.org/documentation/getting-started/configuration/
