### ISSUE TITLE
How to add/edit icon svgs?

### ISSUE THREAD

**Issue by jalemann** [Jieiku/abridge#107]
What are the steps to add or replace icon svgs?

For example I wanted to replace the included codeberg svg which doesn't contain color with [this one](https://de.wikipedia.org/wiki/Datei:Codeberg_Logo.svg) containing color

**Comment by Jieiku** [comment]
Here is the commit where I added both the codeberg and discord icons:

https://github.com/Jieiku/abridge/commit/7207c18e0a5b751c4580c6a6ccb9f1f605974604

If all you want to do is change the color of the existing icon then you would just change the colors 555 and aaa to whatever color code you want:

https://github.com/Jieiku/abridge/blob/75bb461162f7644a498101bc121faac3cfee7799/sass/include/_icons.scss#L83
