### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#12]
I'd like to encourage you to make a small "search" button next to the search bar for users who otherwise don't think to hit enter

**Comment by Jieiku** [comment]
I will see about adding an option for one, of all the zola themes I think I only seen one that had a search button: https://www.getzola.org/themes/zolastrap/

**Comment by simbleau** [comment]
Maybe a button wouldn't be so important I suppose - users are not as bad as I made them out.

But in the way, I did think that there could perhaps be an inlayed icon for some jazz:
![2022-05-06_10-34](https://user-images.githubusercontent.com/48108917/167154981-d52412d6-38b6-46ca-af29-56b28a2c35d3.png)
or this:
![2022-05-06_10-38](https://user-images.githubusercontent.com/48108917/167155164-13fced33-4b80-4791-871d-b55225c3c723.png)

**Comment by Jieiku** [comment]
I have made a good amount of progress on this, I will push it once I am done rewriting some of the javascript for the search functionality.

![2022-05-11_22-01-51](https://user-images.githubusercontent.com/106644/167995595-53b927e7-0f5e-4613-9d5e-8444af833b95.png)

**Comment by Jieiku** [comment]
This one was fun, and now my search does something that as far as I am aware none of the other Zola themes do.

**Comment by Jieiku** [comment]
The search button looks correct in Firefox but is doing something weird in chrome, will figure it out tomorrow.

**Comment by simbleau** [comment]
Excellent work so far!

**Comment by simbleau** [comment]
One particular thing I'd like to see is the same rounding on the search bar as the rounding on the "recent posts" box. :)

**Comment by Jieiku** [comment]
I played with the border radius and forgot to set it back when I was inlaying the icon, you can take a look now.

Fixed the Search Icon too.
