### ISSUE TITLE
Failed to serve and build the theme Error: Reason: Function 'get_hash' not found

### ISSUE THREAD

**Issue by wewlad-dev** [Jieiku/abridge#126]
OS: Windows 10 x64
zola 0.16.1

Zola works fine and so is other themes, trying Abdridge, using the default settings on everything results in an error as follow:

`Error: Failed to serve the site
Error: Failed to render section '\\?\C:\Users\null\blog\content\posts\_index.md'
Error: Reason: Failed to render 'posts.html': error while rendering macro `macros_head::theme` (error happened in 'base.html').
Error: Reason: Function 'get_hash' not found`

How to solve that?

**Comment by Jieiku** [comment]
Upgrade Zola to latest:

https://github.com/Jieiku/abridge/blob/5c3cc8966834a0d140f82aa178ba26109f79dd8f/theme.toml#L5

If you absolutely have to you could use an older version of abridge, but I would not recommend it, better to upgrade zola: https://github.com/Jieiku/abridge/releases

This was a result of a change in Zola, where the function name changed, here is when abridge changed to match it: https://github.com/Jieiku/abridge/issues/104

**Comment by wewlad-dev** [comment]
Right, thanks for pointing my ignorance! 😁
It seems Chocolatey still didn't updated it, as I installed it a couple days ago, just upgraded Zola manually and now it works great, thanks again!
