### ISSUE TITLE
[Feature Request] Allow for a custom copyright to be set

### ISSUE THREAD

**Issue by samueloph** [Jieiku/abridge#127]
I couldn't find a way of setting a custom copyright license, so resorted to manually modifying `templates/base.html` to change it.

It would be nice if the copyright license could be change through `config.toml`.

**Comment by Jieiku** [comment]
The abridge theme uses an MIT license, but the theme itself displays a generic copyright which is meant to be used for your content and not the theme itself.

I am assuming your talking about this:

![2023-07-16_19-02-35](https://github.com/Jieiku/abridge/assets/106644/1cac515c-ee51-47a6-adb0-288752c1bae5)

The year is automatic and a start date can be set, the name  "Abridge" is set according to the site title. 

The line for the copyright is here: https://github.com/Jieiku/abridge/blob/5c3cc8966834a0d140f82aa178ba26109f79dd8f/templates/base.html#L100

However in the refactor branch I actually already made a change to this:

https://github.com/Jieiku/abridge/blob/d367a4b79c801ac0ac084032aaee388616ffe97c/templates/base.html#L126

**Comment by samueloph** [comment]
> I am assuming your talking about this:

That's exactly the one I'm talking about, sorry for not being descriptive enough.

> What kind of changes are you looking to make? is it just the "Copyright ©" you want to override? or maybe using something other than the title?

I would like to be able to set a custom license for the contents of the site, "Copyright ©" does not mention any licenses, so to give an example of what I would like to have instead:
> © $author. Unless otherwise noted, the content in this website is available under the [CreativeCommons Attribution-No Derivative Works 3.0 Unported](http://creativecommons.org/licenses/by-nd/3.0/) license.

**Comment by Jieiku** [comment]
This is completed in the refactor branch, which will be merged once the next version/subversion of Zola is released.

https://github.com/Jieiku/abridge/commit/b53294f7fb8afbb9565dcd46f2985257c8075e5c
