### ISSUE TITLE
Suggestion to further improve dark mode + appreciation post

### ISSUE THREAD

**Issue by IngrownMink4** [Jieiku/abridge#136]
**First of all, I would like to thank you for the great work you have done with Abridge! It is the theme for Zola that I like the most by far. In fact, I'm seriously thinking about using it for my next website :) That said, thank you very much for working on this and for making it open source!**

## The suggestion
So, Abridge currently respects the user's preference of dark and light appearance when visiting the web page, and even provides a switch to force one appearance or the other (that's cool).

However, the dark mode could be further extended. [Web forms and scrollbars](https://concrete-hardboard.glitch.me/) in Chromium-based browsers still look light and are very out of place with the dark look (in Firefox the scrollbars automatically adapt to the look of the page, so only web forms are affected). This could be solved by using the CSS `color-scheme` property. [This post](https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does) explains it in detail. 

I attach images of what it looks like now and what it would look like with the CSS property enabled. Thank you <3.

![Captura desde 2023-08-23 17-51-13](https://github.com/Jieiku/abridge/assets/25466522/f00f3dae-b5a8-4b7e-becb-6bd65f54c1cb)
![Captura desde 2023-08-23 17-52-28](https://github.com/Jieiku/abridge/assets/25466522/2af73cc8-6545-4daf-957f-c5dbd18ef59e)

**Comment by Jieiku** [comment]
Excellent, will do this for sure. Currently working on another batch of commits as well, more updates coming very soon.

**Comment by Jieiku** [comment]
This is now completed in a local commit, you will see it sometime today or tomorrow.

**Comment by Jieiku** [comment]
On a side note I also made some improvements to the table of contents spacing, it now makes more efficient use of the space and should allow more items before overflowing into adding a scrollbar

**Comment by Jieiku** [comment]
completed: https://github.com/Jieiku/abridge/commit/c04ff0a3ac2aff149c3454f7563de3f7941e373d

**Comment by IngrownMink4** [comment]
Wow, that was really fast! Thanks again :D
