### ISSUE TITLE
different color for visited links

### ISSUE THREAD

**Issue by itf** [Jieiku/abridge#137]
It would be nice to customize the color of visited links, a:visited

**Comment by Jieiku** [comment]
I almost misread this and was going to say it is already possible to change the color of links.

You are absolutely correct, that would be good to have. I will add a css var for that.

**Comment by Jieiku** [comment]
sorry for the delay on this, it is now completed, by default I set the value to be the same as the normal links, so it won't be obvious in the demo.

My take on it is that it kinda makes some pages/links look messy... for instance the tags, however I am not a color expert, so maybe another color would have looked fine.

The css variable is there now and available for customization in the override file:

https://github.com/Jieiku/abridge/blob/1ceb421f09f8a5fbd639382a4e4dbccd4584744e/COPY-TO-ROOT-SASS/abridge.scss#L84

If you have any other feedback regarding this issue just leave me a comment here.
