### ISSUE TITLE
Clearer instructions in readme and scss file

### ISSUE THREAD

**Issue by Hysterelius** [Jieiku/abridge#138]
First of all, I would like to praise you on the amazing work you have done on the abridge project. While using it, I came across a few minor issues and things you could clear up in the documentation with the newest version (I am using the latest commit).

I have had to create my own `.scss` file to import custom fonts into the project, like the `Roboto.scss` file. This could be made a little clearer.

https://github.com/Jieiku/abridge/blob/009d3f90b1881530bd28003abe83cfc3735882be/sass/fonts/_Roboto.scss#L1-L17

I also found that in order to prepend the fonts file, it is necessary to use null on lines 127-128 of the `abridge.scss` file which is undocumented. 

https://github.com/Jieiku/abridge/blob/009d3f90b1881530bd28003abe83cfc3735882be/COPY-TO-ROOT-SASS/abridge.scss#L127-L128

Furthermore, while using the abridge switcher, I had to change the value of `switcherDefault` to `light` to make my code block formatting be of the same colour theme as the rest of my website. Is this the intended behaviour?

https://github.com/Jieiku/abridge/blob/009d3f90b1881530bd28003abe83cfc3735882be/COPY-TO-ROOT-SASS/abridge.scss#L13

I would be more than happy to contribute to this project by submitting a PR. Thank you for your time and consideration.

**Comment by Jieiku** [comment]
Ah yes, null is used if you want to prepend the list instead of append. very good point will add this info.

`Furthermore, while using the abridge switcher, I had to change the value of switcherDefault to light to make my code block formatting be of the same colour theme as the rest of my website. Is this the intended behaviour?`

No, definitely should not be doing that: you can see that in the demo it works properly: https://abridge.netlify.app/overview-code-blocks/

I suspect the issue here is cache related, try Ctrl+shift+P to open a private browsing session. If the issue persists then I would ask if the source code for your website is in a repo so that I could take a look.

**Comment by Jieiku** [comment]
I added examples and documentation for the fonts:

https://github.com/Jieiku/abridge/commit/c5274a698be209d02f4d8833cecc72a909cc5edf

I am not going to close this issue yet though, because I am curious about your code blocks....

Let me know what your able to figure out with those, Thanks!

**Comment by Hysterelius** [comment]
This what my website looks like when `switcherDefault` is set to `light`:
 
![switcher-light-abridge](https://github.com/Jieiku/abridge/assets/71912794/5a9c9cea-4d2c-401a-a260-1a0fa2689d98)

Then what it is like when `switcherDefault` is set to `dark`:

![switcher-dark-abridge](https://github.com/Jieiku/abridge/assets/71912794/af141e16-606d-4a3f-a0ae-6d494903a203)

Thanks for all your work on the documentation front.

**Comment by Jieiku** [comment]
I checked your github, does not seem your sites source is in a public repository.

If you want to upload your site to a repo minus your content and redact anything sensitive in config.toml then I could take a look and probably figure it out.

The first thing I would do if I had it in front of me is doing a diff between the root sass/abridge.scss as well as the config.toml

I am interested in this not only to figure it out for you, but also others that may run into the same issue. It does not happen on a fresh install:

```
git clone https://github.com/Jieiku/abridge
cd abridge
zola serve
```

**Comment by Hysterelius** [comment]
I am more than happy to make the repo and make it public, but I am currently unable. Give me a couple of hours, and I'll have a look then :)

**Comment by Hysterelius** [comment]
I've just added you to my repo. I've found something very odd, when I run `zola serve` the website I get uses my custom `abridge.scss` but when I run `zola build` it uses the default `abridge.scss`.

**Comment by Jieiku** [comment]
I was just headed to bed, planning to take a look tomorrow :) any files named the same locally should be used over the theme files, at-least that has been my experience so far.

**Comment by Jieiku** [comment]
I pushed a commit to your repo. You had sass directory in the .gitignore. Which might have been appropriate under the old abridge. Now however we use a scss overrides file for customization in that directory.

I also cleaned up some differences in the config.toml.
copied the new sass overrides file in place, and added your customized colors to it.

All in all not too bad, only took like 20 minutes to fix any issues that I am able to see.

![hysterelius](https://github.com/Jieiku/abridge/assets/106644/87bd48e5-6dc1-4645-b745-93aa6f4534cc)

Make sure to check it over good for any other customizations I might have missed.

It seems the npm scripts are currently tuned to work from abridge theme, I was working to minimize the number of entries at one point for the package.json. So I will have a look at that once I get a little bit more free time, probably in a day or two.

Have a great weekend.

**Comment by Jieiku** [comment]
ahhh the fonts, ill push a commit for those now, 1 sec.

**Comment by Jieiku** [comment]
One thing I noticed while putting your custom font in place, then using ctrl+f5 to refresh the page, is that the fonts appear to download twice in the developer console. I believe this is because of preload.

I just made a note to investigate this later. (the font is however working)

**Comment by Hysterelius** [comment]
Thank you for all your help, especially with fixing my repo. I am just cleaning up a few things and then I'll make it public. Thanks again for all your help :)

**Comment by Jieiku** [comment]
oh no worries if you want to keep your site's source code private, I only made that comment previously because I was not sure how else to get access in order to look it over and help (had not occurred to me you could just ad me as a user).

**Comment by Hysterelius** [comment]
No problem at all, I am more than happy to make it public - I just need to adjust a few things.

Thanks again, and if you would like me to help with anything let me know.

**Comment by Jieiku** [comment]
Thanks, I will let you know if I think of anything. I am planning to do the initial work on the npm scripts. I am going to do a total refactor: #140

**Comment by Jieiku** [comment]
I finished refactoring package.json. there is now really only one npm script to run, and it dynamically handles everything by first parsing your config.toml

`npm run abridge`

I will point out that if you were hoping to test tinysearch or stork you may have to wait a while, there seems to be an issue and I do not have time to investigate it: https://github.com/tinysearch/tinysearch/issues/175

I also tried stork again and ran into similar issues.

Elasticlunr is however working without issue.

**Comment by Hysterelius** [comment]
I have just tried to run `npm run abridge` and I have discovered just one or two minor issues. (I'm not sure if they are specific to my system or not)

I had to edit this line:
https://github.com/Jieiku/abridge/blob/5e55301cc2c91a5f0e99000bfe4d7ec262ee78c1/package_abridge.js#L224

To be `process.stdout.write(....`, otherwise it through an error for me.

Also, I had to copy across the `manifest.json` file, is it a default file or will I have to edit it?

Thanks for all your awesome work!

**Comment by Jieiku** [comment]
Just pushed a commit that will check if the manifest.json file exists before attempting to minify it.

manifest.json is used by PWAs, its what gives them a list of icons to use for various phones, tablets, etc.

**Comment by Hysterelius** [comment]
My website isn't a PWA, so I don't need a `mainfest.json`?

**Comment by Jieiku** [comment]
yeah, you should be fine without it if you set pwa = false in config.toml

did you pull the commit I just pushed? https://github.com/Jieiku/abridge/commit/9c6f4e078620b4d9d2ddf2ad17bdd3b97aa28704

**Comment by Jieiku** [comment]
Thanks for testing the latest changes, and the feedback!
