### ISSUE TITLE
Proposal: Create Series Block

### ISSUE THREAD

**Issue by Hysterelius** [Jieiku/abridge#143]
Hi,

I'm currently implementing a series feature for abridge, a bit like this:

![image](https://github.com/Jieiku/abridge/assets/71912794/0bfc98bb-57eb-43d1-b725-291f9e0a19ea)

It would be so that you could link a series of articles together that were based around a particular theme.

I was thinking of basing it off tags/categories, or maybe even a whole new taxonomy. I was trying to write it as a `shortcode` then I noticed this:

> Shortcodes are rendered before the page's Markdown is parsed so they don't have access to the page's table of contents. Because of that, you also cannot use the [get_page](https://www.getzola.org/documentation/templates/overview/#get-page)/[get_section](https://www.getzola.org/documentation/templates/overview/#get-section)/[get_taxonomy](https://www.getzola.org/documentation/templates/overview/#get-taxonomy)/[get_taxonomy_term](https://www.getzola.org/documentation/templates/overview/#get-taxonomy-term) global functions. It might work while running zola serve because it has been loaded but it will fail during zola build.[^1]

[^1]: https://www.getzola.org/documentation/content/shortcodes/#writing-a-shortcode

So, I will probably have to write a macro to access the taxonomy functions, so I was wondering if I could get hand with this? I am more than happy to write the macro itself, but I will probably need some help implementing it.

**Comment by Jieiku** [comment]
Do you know if a similar feature exists in any of the other themes? if so it could be used as a reference, if not then it could be made from scratch.

It kinda sounds similar to what I did for the Recent Posts block.... I think I seen something like this here:  `https://docs.nosqlbench.io/`

Might be a similar feature in one of the other themes as well, will have a look tomorrow.

**Comment by Hysterelius** [comment]
I have had a quick look, I haven't been able to see anything :(

Due to the limitation I mentioned before, the only way I can see doing it is wrapping each `page.html` in a macro which would generate the series list. Then it could be shown by a shortcode, but my knowledge of Zola is _very_ limited...

**Comment by Jieiku** [comment]
well I love this idea, but wont have time to work on abridge much for the next couple weeks, a really big project just started at work and I will be working overtime for a bit.

I wonder if Zola's section feature could be used to do this... I am sure it could, but I am not sure if its the best way to do it or not. https://www.getzola.org/documentation/content/section/

I am happy to help with this when I finally get some free time.

**Comment by Hysterelius** [comment]
I am happy to just work on it for a few weeks, and we can see how I go

**Comment by Jieiku** [comment]
ahhh, you could have said a lot of that scss was exactly how the .toc scss was. This is why I generally stick to semantic html styling, its simpler and cleaner. So basically we have the same scss for both the toc and the series, which pretty much duplicates most of it.

Most of the code for the original toc actually came from juice: https://juice.huhu.io/

Going to try and refactor most of it right now and see how much of the class based attributes can just be removed entirely.

**Comment by Hysterelius** [comment]
Sorry, yeah I probably should have said something 

You are correct with them both being the same css.

**Comment by Jieiku** [comment]
Yep, would have been helpful, but not your fault. I had not worked on the ToC in a while so I forgot about all those class definitions. This is actually good because it should be much lighter after the refactor and we will have some reuseable classes for any other blocks that get added to the side columns.

**Comment by Jieiku** [comment]
I actually have a really interesting idea for a side block too. something like "Top Posts" If you have access to server logs or analytics then you could parse that data and make a block containing the most popular posts. (this has been on my todo list for a while)

**Comment by Jieiku** [comment]
I just updated Abridge so that it demos the new Series Block. I also updated it to sort by date instead of year.
