### ISSUE TITLE
Enhancement: toggle darkmode button

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#15]
Please add a toggle darkmode button

**Comment by Jieiku** [comment]
I will look into if I can add a toggle darkmode button that is disabled by default, then you can enable it.

The reason for this is here my first response here: https://github.com/Jieiku/abridge/issues/10

If I can add it in a way that by default it does not increase the size of the css or js unless enabled then I will, no promises on this one though.

**Comment by simbleau** [comment]
This is exciting

**Comment by Jieiku** [comment]
Made more progress on this, its working well, going to do a bit more testing and cleanup before commit.

**Comment by Jieiku** [comment]
This wont be implemented if I cannot fully resolve the page flicker, or if I do it will be disabled by default.
Also colors through config.toml was not doable.

Here is the problem I am trying to avoid:

![flash](https://user-images.githubusercontent.com/106644/172444327-e6fab5a9-f968-4753-8ef6-7da7a57c4806.gif)

My implementation does not flash most clicks, and when it does it is nowhere near this bad, but I do occasionally still get some flashes, and it seems most themes that implement this feature have this issue to some extent.

**Comment by Jieiku** [comment]
I got everything related to this feature request resolved, just doing some cleanup and documentation before commit.
