### ISSUE TITLE
Recent TOC item padding changes

### ISSUE THREAD

**Issue by wold5** [Jieiku/abridge#152]
Hi, after updating to 2.3.0, a change in the padding of the TOC items has become noticable. This is with FF118 on Linux Debian.

1) Adding the top-padding back would improve the overall look, IMHO.

2) The top/bottom space for the H4 (now .b) items also helped, but seems optional.

Your thoughts?

![abridge-200-headerissue](https://github.com/Jieiku/abridge/assets/39151888/28a1a3ce-8dbb-40ac-9642-4b32d0381cca)

BTW, nice updates, the `archive.html` rename, and the `posts.html` content block simplifications, amongst others.

**Comment by Jieiku** [comment]
Thanks, Some very large pages can have very long index. The idea was to make better use of the space. I just added a bit of top padding to the blockdiv which I agree looks a bit better.
