### ISSUE TITLE
Translation request of "Results For:" in i18n toml files

### ISSUE THREAD

**Issue by DaniSancas** [Jieiku/abridge#153]
Hi @Jieiku, first of all thank you very much for your hard work and effort on Abridge Zola Theme.

I have [my blog](https://danisancas.com/) for almost a year now and that's my theme since the beginning :raised_hands: 

Continuing with my petition:

I have my blog entirely in spanish (not using multilanguage feature) and today I'm thinking about enabling the search. I see that automatically the search bar text is "Buscar" instead of "Search" which is amazing! However, if I search something I see that the result string is "Results For: your_search_term". I think it would be perfect if that string could be included in `i18n/es.toml` file (and for other languages as well).

![image](https://github.com/Jieiku/abridge/assets/3708682/5cac7b56-39e2-4bd2-a823-2195103d281b)

Thank you again for everything! Let me know if you need something else to help you with this request.

**Comment by Jieiku** [comment]
The translations normally come from Zola, but zola cannot build js file. I think instead simply using a search icon would be sufficient:

![2023-10-22_11-16-36](https://github.com/Jieiku/abridge/assets/106644/7bb12c79-b7d6-409d-93c7-6255ada8e687)

**Comment by Jieiku** [comment]
Fixed: https://github.com/Jieiku/abridge/commit/8bca9db5ecb24813e83f5e5bdd2bf87c16ba06e4
