### ISSUE TITLE
npm run abridge problem due to missing js folder in static folder

### ISSUE THREAD

**Issue by leehbi** [Jieiku/abridge#155]
Hi 
I thought I'd test out the npm run abridge script on my dev machine before deploying to Netlify.
It failed with :

Error: ENOENT: no such file or directory, copyfile 'themes/abridge/static/js/sw_load.js' -> 'static/js/sw_load.js'

I confirmed the file is there.   Note I'm running WSL on Windows 10.

I have Node.js v20.9.0 LTS

I did run NPM install prior to running.   I fixed the issue by created a js folder in the blog route : static/js 

This is mostly for anyone else that runs into that.  I guess for most folks it's obvious problem but I didn't know the path was needed in the destination.

**Comment by Jieiku** [comment]
Thanks very much for reporting this, I will modify the script to create the directory if it is missing.

**Comment by Jieiku** [comment]
This is now fixed: https://github.com/Jieiku/abridge/commit/8fd6b499763eaecccee56004a4b3e8ec1fc34b7c

Thanks again for the report, let me know if you run into anything else.
