### ISSUE TITLE
Netlify deploy uses abridge.netlify.app domain instead of netlify subdomain

### ISSUE THREAD

**Issue by Brandon689** [Jieiku/abridge#159]
Im not sure why, changing base url in config doesnt affect it, then of course the website loads with no css / js because of cors. From what I understand $DEPLOY_PRIME_URL should automatically resolve to the correct domain.

**Comment by Jieiku** [comment]
in config.toml do you have `pwa = true` or `pwa = false` ?

If you have `true`, then did you run:

`npm install
npm run abridge`

prior to deployment?

I am not certain this is the cause of your problem, it is just a guess without looking at your sites config files and the feedback from netlify deploy.

**Comment by Jieiku** [comment]
another suggestion is to try with `pwa = false` initially. and redeploy.

Then clear your browser cache or hold down control and press F5 to force a reload that bypasses all cache.

Then see if the page loads properly.

**Comment by Brandon689** [comment]
Im trying now

**Comment by Jieiku** [comment]
Thanks for the repo, testing it out now.

**Comment by Jieiku** [comment]
Just wanted to let you know I am seeing the same thing https://zola-themes-demos.netlify.app/

I am eating dinner and it is close to bed time, but will figure this out once I examine it closer.

I am sure it is something simple that I am overlooking.

**Comment by Brandon689** [comment]
Thank you, no need to rush, I'm doing other work for now.

**Comment by Jieiku** [comment]
I figured this out after experiencing the same thing.

You have to set both in config.toml:

```
base_url = "https://example.netlify.app"
online_url = "https://example.netlify.app"
```

online_url exists to facilitate generating an offline site then restoring the base_url for online site. I can see this will be problematic for new users, even I forgot about adding this functionality.

**Comment by Jieiku** [comment]
seems to be working for me

repo: https://github.com/Brandon689/blognetlify/compare/main...Jieiku:blognetlify:main

site: https://zola-themes-demos.netlify.app/

**Comment by Brandon689** [comment]
I've got it to work now, well not quite because its now using my domain which take a bit of time for DNS, but I think the problem I mentioned is real. So I would add some docs about deploying to netlify and from github.
Its actually confusing because when you make a netlify site you dont have the domain they give you, it doesnt exist yet. So you have to re-deploy.

Also some comment to check your remote origin that the config.toml of your site is correct, not just your local. Finally I would move online_url to be below base_url in config maybe.

**Comment by Jieiku** [comment]
I am planning to blow the site and repo away and retest now that I have made a change to `online_url`. https://github.com/Jieiku/abridge/commit/ae68172b9b6a2bdbe620fd36589a6151cee5df28

I need to be certain of the exact cause before adding instruction to the docs.

**Comment by Jieiku** [comment]
When I originally cloned your repo I was having the same issue you pointed out, at that point in time online_url was not set and was still abridge.netlify.app which is why the base_url kept changing to that.

I have since made some changes to online_url: https://github.com/Jieiku/abridge/commit/ae68172b9b6a2bdbe620fd36589a6151cee5df28

I attempted to retest this, and can no longer reproduce the issue. I believe the root cause was online_url and it may have also been made worse if the pwa was active.

**Comment by Jieiku** [comment]
Thanks again for this report, my hope is that abridge will now be easier to use for all. the online_url is only necessary for those that test offline = true so having it commented out by default makes sense to me, since most people will probably not be using that feature anyway.
