### ISSUE TITLE
Question about 'Body' variable in katex shortcode

### ISSUE THREAD

**Issue by itstamimi** [Jieiku/abridge#163]
The 'body' variable in here
https://github.com/Jieiku/abridge/blob/d45bc26c2250f573a0d83f755831857999fc125f/templates/shortcodes/katex.html#L1
it's coming from where?

I'm asking as I'm making a shortcode for something else, and the expression {{ }} I have in the short code script works fine, but because of the CSP whenever the value changes, the hash changes too making the shortcode unusable. I was looking at katex and it seems there's a way by having the expression {{ }} in the post itself rather than the script, and that might solve it, it's just I don't know the "body" variable is taken from where.

Thanks!

**Comment by Jieiku** [comment]
The body variable is a built in feaure of Zola:

https://www.getzola.org/documentation/content/shortcodes/#shortcodes-with-body

I had similar issues when I initially implemented a imgswap shortcode: https://abridge.netlify.app/overview-images/#imgswap-shortcode

Initially I was trying to do it in a way that the src changed, but instead I just include both image sources in the body of the page with different class names. You may have to think outside of the box depending on what your trying to accomplish.
