### ISSUE TITLE
Issues with `next` v0.18+

### ISSUE THREAD

**Issue by wold5** [Jieiku/abridge#164]
Hi, Abridge works fine with v0.18, but breaks when testing the current `next` (up to and https://github.com/getzola/zola/commit/4bf67afd875b99d2bad6fe252d6fb6e44f52b313). Thought I'd give you a heads up.

1. Translation menus don't substitute dashes properly:
instead of `/nl/software/` its `//nlsoftware/`
Changing https://github.com/Jieiku/abridge/blob/d45bc26c2250f573a0d83f755831857999fc125f/templates/base.html#L76-L77 to use `to=config.base_url ~ lcode ~ '/')` fixes it for `next`, but breaks 0.18.

2. The logo gets a double `//` in `next`(the config `base_url` omits the dash, as recommended)
It's fixable by removing the dash here https://github.com/Jieiku/abridge/blob/d45bc26c2250f573a0d83f755831857999fc125f/templates/base.html#L37-L38

Of the recent commits these two come to mind:
https://github.com/getzola/zola/commit/4bf67afd875b99d2bad6fe252d6fb6e44f52b313 (--base-url)
https://github.com/getzola/zola/commit/73e06bd4cf0712d2f36675334c29594cb2fb9b34 (get_page/get_section language argument)

**Comment by Jieiku** [comment]
excellent, thank you. I wonder if these are intended changes or not, will keep an eye on the zola release. (I have it watched on github)

**Comment by wold5** [comment]
You're welcome. Will keep building with 0.18 for now.

By chance, having just added a site translation, constructing a section path requires code similar to that linked in (1) 😛 So curious what you come up with. Might even fix it myself 😉

**Comment by Jieiku** [comment]
Zola 0.19 just dropped. I drafted a release of abridge to preserve a compatible version for 0.18.

I am going to take a look at 0.19 now.

**Comment by Jieiku** [comment]
It looks like your original bug report might have been resolved before 0.19 was released, I am not seeing those issue currently. I did however have to disable the feeds in config.toml:

`generate_feeds = false`

I believe it might be related to https://github.com/getzola/zola/pull/2477

I am pretty busy today, but I am going to try and look into it tomorrow.

**Comment by wold5** [comment]
Tonight or tomorrow I'll check this out. Would have done so now, but the whole lot needs syncing and updating, etc.

**Comment by Jieiku** [comment]
I just updated abridge for 0.19.1 so far everything seems OK and the demo is functioning properly.

**Comment by wold5** [comment]
Confirmed, 0.19/0.19.1 works here too, on Windows, with the latest Abridge.

> I did however have to disable the feeds in config.toml:

Same here, otherwise it throws this error, on multiple pages:

```
Error: Failed to serve the site
Error: Failed to render page '\\?\C:\Users\...\syncoda\content\pages\offline.md'
Error: Reason: Failed to render 'pages.html' (error happened in 'base.html').
Error: Reason: Test call 'containing' failed
Error: Reason: Tester `containing` was called on an undefined variable

PS C:\Users\...\syncoda> .\bin\zola-191.exe --version
zola 0.19.1
```

Also had to remove 
```
[languages.nl]
#language_name = "Nederlands" <---
```
which appears to be baked in now, it seems.

Thank you for your responses!

**Comment by Jieiku** [comment]
With the latest abridge you just need to update your config.toml and replace all occurrences of

`generate_feed = true` with `generate_feeds = true`

**Comment by Jieiku** [comment]
> Confirmed, 0.19/0.19.1 works here too, on Windows, with the latest Abridge.

What route do you use to install Zola on windows? I still need to install Zola on windows to test a few things.

**Comment by wold5** [comment]
It works now. The Abridge /themes/ submodule wasn't updated, at the previous version or the long words commit (30dfea21f6e134c706fe5076ce6ff148a011e901). Using multiple machines here...

> With the latest abridge you just need to update your `config.toml` and replace all occurrences of
> 
> `generate_feed = true` with `generate_feeds = true`
> 
> Then after updating Zola to 0.19.1 your Atom feed should work properly.
 
The 0.19 changelog mentioned that variable and `feed_filenames`, so I had changed those. Next I faultily assumed your remark was a WIP fix for the issue described. Good reminder to always check assumptions ;-)

As for Windows, the here used method is:
- the official Rust package from https://www.rust-lang.org/
- `cargo build --target-dir #targetdir#` for a debug build
