### ISSUE TITLE
Upgrade steps?

### ISSUE THREAD

**Issue by cskwrd** [Jieiku/abridge#170]
What are the appropriate upgrade steps?

I have a site using what looks like v1.2. is the only way to upgrade to manually checkout each version and diff the config along the way?

**Comment by Jieiku** [comment]
If you are running abridge as a submodule then you can update it:

```
git submodule update --init --recursive
git submodule update --remote --merge
```

You should diff the config for the changes, which is exactly what I do when I update.
Check config.toml as well as the overrides in the copy to root sass folder:

https://github.com/Jieiku/abridge/blob/master/config.toml

https://github.com/Jieiku/abridge/tree/master/COPY-TO-ROOT-SASS

The abridge.css demo using abridge as a demo, and I recently update it to latest here:

https://github.com/Jieiku/abridge.css/commit/6cbf633b49e0938e2c15be123c026dfd025c31ab

**Comment by cskwrd** [comment]
> You should diff the config for the changes, which is exactly what I do when I update. Check config.toml as well as the overrides in the copy to root sass folder:
> 
> https://github.com/Jieiku/abridge/blob/master/config.toml
> 
> https://github.com/Jieiku/abridge/tree/master/COPY-TO-ROOT-SASS

That is what I thought, thank you!
