### ISSUE TITLE
Add custom social icon and link

### ISSUE THREAD

**Issue by mdev88** [Jieiku/abridge#171]
Hello, thank you for developing this great theme!

I found that there is no option to add a PeerTube channel in the footer, so it would be useful to either add PeerTube as an option, or add the possibility to add custom links.

Thanks

**Comment by Jieiku** [comment]
Completed this a moment ago https://github.com/Jieiku/abridge/commit/400f3f431e3837ec7983930fb41ff89b7092c4e2
