### ISSUE TITLE
Error when disablin multilanguage

### ISSUE THREAD

**Issue by mdev88** [Jieiku/abridge#172]
I don't need my site to be multilanguage. I have tried removing all the aditional languages but I get an error:

`Error: Failed to serve the site
Error: Found path collisions:
- `/index-fr/` from files ["/home/user/Development/zola/hackfun/content/overview-abridge/index.fr.md", "/home/user/Development/zola/hackfun/content/overview-images/index.fr.md", "/home/user/Development/zola/hackfun/content/overview-rich-content/index.fr.md"]
`

I had to leave a dummy language configuration for `fr` because of that error, so the language selector in the header shows my default language (es) and also french, and I can't find a way to disable or hide the language selector.

**Comment by Jieiku** [comment]
When you copied the example content, you must also have the language config for it.

To remove the multilingual features from config.toml you also need to remove the multilanguage content. (all the files under content that end in .fr.md)

**Comment by mdev88** [comment]
I must have missed that. It's fixed. Thanks!
