### ISSUE TITLE
Hard disable favicon?

### ISSUE THREAD

**Issue by qrrcnaxne** [Jieiku/abridge#174]
Hello. I have commented out all the `favicon*`s from `config.toml`. When I do `zola serve` locally the icon doesn't show. However abridge icon shows up on the browser's tab when the [site](https://qrrcnaxne.github.io/) is hosted on github. I had a look at head template and figured it shouldn't show if those config lines are commented out. But whatever magic zola github action does, it includes a `favicon.ico` in [root dir](https://github.com/qrrcnaxne/qrrcnaxne.github.io/tree/gh-pages), and browsers probably just show it as default? I tried creating an empty `favicon.ico` file in static directory: didn't work. 

How can I disable this image completely?

**Comment by Jieiku** [comment]
commenting out the favicons from config.toml is the correct thing to do. You are also correct that the browsers automatically look for a favicon.ico  It is not even defined in the head.

Putting an empty favicon.ico in your static directory should have overridden the one in the theme!

If you look here: https://qrrcnaxne.github.io/favicon.ico

you can see it loads the abridge icon and not your empty one.....

I will give this a try and see what happens.

**Comment by Jieiku** [comment]
I believe you had it when you added the empty favicon.ico your browser simply already had it cashed.

If you had left your empty favicon.ico then cleared your browser cache you would have been good to go.

look here:
https://zola-themes-demos.netlify.app/

and here:
https://zola-themes-demos.netlify.app/favicon.ico

This site was made by forking your site and putting your empty icon back in place.

**Comment by qrrcnaxne** [comment]
Wow you're right, thanks a lot! I added it back and it works in a private window. Couldn't have guessed that it was cached, lol. Thanks for the quick help!

**Comment by Jieiku** [comment]
Can also exclude them:

add this to your config.toml:

```toml
ignored_static = ["apple-touch-icon.png","banner.png","safari-pinned-tab.svg","favicon*","m*.png","android-chrome*png"]
```

found the answer here: https://www.getzola.org/documentation/getting-started/configuration/
