### ISSUE TITLE
Analytics support

### ISSUE THREAD

**Issue by Guekka** [Jieiku/abridge#175]
Hello. Thanks for this nice theme!
I have not found an easy way to load a custom script. My current workaround is to extend the default templates, but that's not really intuitive
I'm currently using Plausible if that matters, but I think a generic solution would be better
What do you think?

**Comment by Jieiku** [comment]
I think it is a good idea. I could have an empty template file to be included in which case your template file could override it and it's contents would get included in the head

We could also just use a config value in config.toml such as this:

head_extra = '<meta name="test" content="tag1" /><meta name="test" content="tag2" />'

Let me know what you think, or if you had any other ideas.

**Comment by Guekka** [comment]
The `config.toml` option is probably the simplest

**Comment by Jieiku** [comment]
done: https://github.com/Jieiku/abridge/commit/dfa40127ea0471488a04fa6cf67c749d429dde46

**Comment by Guekka** [comment]
That was fast, than you
