### ISSUE TITLE
Add ability to specify description

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#18]
Please allow specific descriptions for the main page and pair that with SEO.

If you start a post with an image or anything other than a sentence, you get this:

![2022-05-06_08-36](https://user-images.githubusercontent.com/48108917/167133050-133d623a-8e17-4614-b17b-28ba1ab7010d.png)

**Comment by Jieiku** [comment]
The reason for this is page summary only works if you include the `<!-- more -->` tag

for example:

```
For quick setup copy the config.toml from the abridge theme into the root of your zola site, this will give you a base configuration with all config values used.
<!-- more -->
```

What I can do is make it so that when the `<!-- more -->` tag is missing it falls back to a description value if set in the post.md markdown file. I will add this shortly, today.

**Comment by simbleau** [comment]
That would be incredible! Thanks.

**Comment by Jieiku** [comment]
This is Fixed, it will fallback to configured description value in post.md and if that is also missing then it will use a truncated amount of the page.content.
