### ISSUE TITLE
recent commit breaks search

### ISSUE THREAD

**Issue by fekie** [Jieiku/abridge#183]
Commit a7244a2983538f373c0af2ecfa4d6377584b8063 breaks search. I recently made a new zola project with abridge, and noticed that the search was not working like on the live demo (https://abridge.pages.dev/). I reverted back to when the zola project was just started and search was still not working. I noticed that search recently had an update via this commit so I reverted to the abridge commit before this one and search began to work again. I am on Windows.

The following happens when I try to search using this commit (does not display articles and gives wasm errors in the console). This does not happen when using previous commits.
![image](https://github.com/user-attachments/assets/4f010ca8-863f-49f6-873d-386808eb3581)

**Comment by Jieiku** [comment]
Pagefind is untested on windows. It may be that you cannot use pagefind on windows (yet) but elasticlunr should still work.

I think I see what happened, some of the default js bundles were committed with pagefind active,  I have rebuilt and minified the bundles with elasticlunr active, can you retest?

https://github.com/Jieiku/abridge/commit/8bc88707ca39db73c4fd890fa030b91b20a8e1c8

**Comment by fekie** [comment]
Alright, can confirm it works now 👍

**Comment by Jieiku** [comment]
Perfect, thank you very much for reporting and testing! I really appreciate it!
