### ISSUE TITLE
KaTeX not working

### ISSUE THREAD

**Issue by acgetchell** [Jieiku/abridge#184]
My page isn't rendering on Zola, though amusingly GitHub renders most of it.

https://github.com/acgetchell/myblog/blob/main/content/blog/designing-a-metropolis-class.md

I've uncommented here without effect:

https://github.com/acgetchell/myblog/blob/main/config.toml#L358

**Comment by Jieiku** [comment]
It is not just you, it appears the demo is also broken: https://abridge.pages.dev/overview-math/

I am going to check if this was caused by a recent commit.

**Comment by acgetchell** [comment]
Thanks, it's resolved.
