### ISSUE TITLE
cannot find icons

### ISSUE THREAD

**Issue by fekie** [Jieiku/abridge#185]
On line 254 of the `config.toml` file, we are told to add the icons we need to the following file, but the repository link is broken (https://github.com/Jieiku/abridge/blob/master/sass/include/_icons.scss). I have also uncommented lines for the individual icons and enabled icons in the config. It says that it would negatively impact performance if we loaded the entire fontawesome css file so I wanted to know if there was a preferred built-in way to do this still.

**Comment by Jieiku** [comment]
most of the independent scss files were merged into a single abridge.scss file during the large refactor, it greatly simplified some of the advanced scss features that were added.

Abridge now uses exclusively svg icons, they are very lightweight, however any scss you want can be added to the extra file:

https://github.com/Jieiku/abridge/blob/master/COPY-TO-ROOT-SASS/_extra.scss

I believe fontawesome has a way of loading their icons via scss, but I honestly lost interest in using fontawesome myself and instead I add svg icons to the icons function here as needed:

https://github.com/Jieiku/abridge/blob/8bc88707ca39db73c4fd890fa030b91b20a8e1c8/sass/_functions.scss#L84

It might be possibly to extend that function for user content but it could also be difficult, encoding svg icons into scss is not something just anyone would be comfortable figuring out how to do.

Pull requests are welcome, or if you have an idea you would like to discuss.

**Comment by Jieiku** [comment]
I updated the config.toml to correct the reference to the no longer existing file, feel free to comment if there is anything else you would like to discuss. Thanks again!
