### ISSUE TITLE
Which are the minimal amount of files I need to include in my project to use abridge.

### ISSUE THREAD

**Issue by IPlayZed** [Jieiku/abridge#192]
Hi (again 😄 ),

Which files are the bare minimum I would need to include in my project to make use of Zola's full features?

As far as I understand, there is no need to include the `content` folder?

Thanks in advance.

**Comment by Jieiku** [comment]
I covered this here https://github.com/Jieiku/abridge?tab=readme-ov-file#3-configuration

but to elaborate farther:

`config.toml` is required but 99% of the values in this file are optional, meaning abridge will build even if they are missing, but it is much simpler to just copy it over and modify what you need.

`content/_index.md` this file controls the pagination, it is required.

`rsync -r themes/abridge/COPY-TO-ROOT-SASS/* sass/`   these files are technically not required if I recall correctly but this is where some of the customization is done.
