### ISSUE TITLE
Bug: Description doesn't work as intended

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#20]
Description/summary/truncated summary(739f3ff9ded912919442e0fadec99d2d0bbcc58c) does not appear to work from my end.
![2022-05-06_12-22](https://user-images.githubusercontent.com/48108917/167173430-715d83f8-f400-4c8e-9d48-2adca0517729.png)

**Comment by Jieiku** [comment]
hmmm I did test it before committing this change.

Here you can see I removed the `<!-- more -->` from the .md file and I added a description.

![2022-05-06_09-55-57](https://user-images.githubusercontent.com/106644/167178121-cda9f069-8f7c-4f7f-bf9b-647e6c42f409.png)

The only thing I can think is for some reason you dont have the latest changes, can you double check the source code of the template?

abridge/templates/index.html (lines 7 - 20)

```
      <article>
        {{ macros::title(page=page) }}
        <p>
          {% if page.summary -%}
            {{ page.summary | markdown(inline=true) | safe }}
          {% elif page.description %}
            {{ page.description | safe }}
          {% elif page.content %}
            {{ page.content | safe | striptags | truncate(length=150) }}
          {% elif page.extra.static_thumbnail %}
          {% endif -%}
          <a href="{{ page.permalink | safe }}">...more</a>
        </p>
      </article>
```

**Comment by Jieiku** [comment]
Maybe visual studio code is doing something weird.... I do all of my coding in either kate or atom.

**Comment by Jieiku** [comment]
If your template is indeed up to date try changing the template change this:

...more

to

...more more more more more

and see if the change takes affect.

**Comment by simbleau** [comment]
Ugh, yuck, you were indeed right. My submodule wasn't updated. Sorry ;P 

I did `git submodule update --init --recursive` and it didn't pull changes; had to go into themes/abridge and do a git pull.
