### ISSUE TITLE
Footnote backreferences?

### ISSUE THREAD

**Issue by adigitoleo** [Jieiku/abridge#200]
Thanks for the nice theme. Can we get footnote backreferences? So the `footnote-reference` sup tags should set an id that `footnote-definition` can refer to? I think it should be possible with just CSS?

Cheers.

**Comment by Jieiku** [comment]
Is this the feature you are talking about:

https://welpo.github.io/tabi/blog/mastering-tabi-settings/#fn-2

![2024-08-19_08-38-35](https://github.com/user-attachments/assets/32b4403b-78e2-46ba-ae22-e2a7c190c0ba)

**Comment by Jieiku** [comment]
hmmm reading that page it may actually be a built in feature now:

https://welpo.github.io/tabi/blog/mastering-tabi-settings/#footnote-backlinks

Zola v0.19.0 and later can do this natively. Set bottom_footnotes = true in your config’s [markdown] section.

**Comment by Jieiku** [comment]
Seems this feature is built in to zola now: https://github.com/getzola/zola/pull/2480

I just enabled the feature in the demo:

https://github.com/Jieiku/abridge/commit/f7f01e6eafe7253312a3bed789a2338a648b074d

https://abridge.pages.dev/overview-markdown-and-style/#fn-1
