### ISSUE TITLE
Support for setting hour in `date` of posts

### ISSUE THREAD

**Issue by samueloph** [Jieiku/abridge#205]
When setting the post's date, as in https://github.com/Jieiku/abridge/blob/642b8c5ec780eb4801c0c0fa133e1479feb4472f/content/overview-abridge/index.md#L4, it doesn't look like it's possible to chose the hour as well.

This is a feature request to support setting the hour in there (it's fine to assume GMT).

Currently, the hour is always set to `T00:00:00+00:00`, and it's not so great for consumers of the RSS feed if they aggregate multiple other blogs, if other blogs have their entries with the correct time, then the one using abridge will show up as an older post and it might be missed.

For example, if the post was made at 18:00 GMT, abridge will still set the time as 00:00 GMT, and when aggregating the feed with other blogs, the other blog's earlier posts (let's say they posted something at 06:00 GMT) will show up as newer than the one created at 18:00 GMT.

**Comment by Jieiku** [comment]
I had not considered the RSS feeds, Zola does support this: https://www.getzola.org/documentation/content/page/#front-matter

The format per Zola's docs is RFC3339 (2002-10-02T15:00:00Z)

I have updated the posts in abridge to include the time: https://github.com/Jieiku/abridge/commit/84b1422c1cf45137988941c978449d81f56e24d0

**Comment by samueloph** [comment]
Awesome, so that was just me being dumb

**Comment by Jieiku** [comment]
after reading about RFC3339 a bit, I found that only specifying Z will set it to UTC, but you can apply an offset as necessary https://stackoverflow.com/questions/33721073/how-to-interpret-rfc3339-utc-timestamp

So you could set it to say 2002-10-02T15:00:00Z+02:00

**Comment by Jieiku** [comment]
One option is maybe to just type into google "what is my UTC time now" and just use that date/time when you set the date in the post.

**Comment by Jieiku** [comment]
One option is to just use the current UTC date and time when you set the date in your post.

On linux you can type this into the command line: date `--utc '+%FT%H:%M:%SZ'`

**Comment by Jieiku** [comment]
If you want to specify the timezone offset then just drop the Z from the end:

https://github.com/getzola/zola/issues/2637
