### ISSUE TITLE
og:locale is hardcoded to "en_US"

### ISSUE THREAD

**Issue by choan** [Jieiku/abridge#207]
The seo macro outputs the meta og:locale as harcoded "en_US".

It should use the locale as set in content.

May I propose a fix?

**Comment by Jieiku** [comment]
Thanks for the report, I just fixed it: https://github.com/Jieiku/abridge/commit/26f386d2d66779a25f91dc688ce44ff768ac1cf9

**Comment by choan** [comment]
Wonderful, thank you so much.
