### ISSUE TITLE
Bug: Pagination always shows even if there are not enough articles for multiple pages

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#21]
Before:

![2022-05-06_13-30](https://user-images.githubusercontent.com/48108917/167182756-59c0e75d-ad8f-4c62-b7c3-55dc79e728c3.png)

After: 
![2022-05-06_13-30_1](https://user-images.githubusercontent.com/48108917/167182800-7445e268-af24-4ea3-9648-e09a054dc28c.png)

**Comment by Jieiku** [comment]
Fixed, thanks!
