### ISSUE TITLE
Support additional per-page stylesheets

### ISSUE THREAD

**Issue by spectria-limina** [Jieiku/abridge#212]
Hi,

I am trying to do some custom SVG animation work, and to support this I need additional stylesheets. For ease of use, I would like to have them as additional per-page stylesheets.

Can you please add support for a `pages.extra.stylesheets` or similar?

It might also be nice to have an overridable block somewhere inside the `<head>` element to put extra content in.

**Comment by Jieiku** [comment]
Sounds good to me: https://github.com/Jieiku/abridge/commit/f69dd7bea484866c9993ba06adb00ac912b5a3ba

I made it similar to the existing entry in config.toml, so you would use it like this:

[extra]
stylesheets = [ "extra1.css", "extra2.css" ]

**Comment by spectria-limina** [comment]
Perfect, thanks for the quick update!
