### ISSUE TITLE
Bug: author_show

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#22]
TLDR https://github.com/Jieiku/abridge/commit/1bedd745f44fb7ed502d376aaf053b40abc0fcbd#commitcomment-73060271

**Comment by Jieiku** [comment]
oh interesting, I will see if I can reproduce this, at first glance it looks like an unclosed tag.... some stuff in your picture appears to be links when it should not be.

**Comment by Jieiku** [comment]
Let me know if that fixes it, I think it will as that was an orphaned closing tag, but I was not actually having the same problem caused by it on my end.

**Comment by Jieiku** [comment]
there was a couple class references from the example I used, I just removed those as well. I do not see any other issues.

**Comment by simbleau** [comment]
Fixed
