### ISSUE TITLE
Can we get footnotes on the same line?

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#24]
It's not exactly "compact". I searched the settings but couldn't find how to modify this...

![2022-05-08_18-32](https://user-images.githubusercontent.com/48108917/167318489-c0d7cb38-8e20-4158-a79f-6eac0c2fb66a.png)

**Comment by Jieiku** [comment]
more compact sounds good to me, will take a look at this.

**Comment by Jieiku** [comment]
going to work on this one now.

**Comment by Jieiku** [comment]
This is done, thanks for the idea.
