### ISSUE TITLE
option to remove all references to social media

### ISSUE THREAD

**Issue by craftyguy** [Jieiku/abridge#3]
would you be open to a patch that conditionally adds social media references? for instance, I noticed a lot of "twitter"-related tags are in the generated html when this theme is used, even if there are no twitter accounts in the config.toml. I'm allergic to things like twitter, but understand others find value in having that stuff set in the generated site, so the option could be enabled by default so current behavior is preserved. What do you think?

**Comment by craftyguy** [comment]
specifically I'm referring to stuff like:
```
<meta name="twitter:description" content="{{ page.description }}">
```

but it might be nice to just have a way to remove that and opengraph stuff too for folks that don't care about SEO...

**Comment by Jieiku** [comment]
absolutely, sounds good to me.

**Comment by Jieiku** [comment]
Also, even if you do not use twitter, some of those meta tags related to twitter help when OTHER people post a link to your article on twitter, same with the facebook meta tags.

I also do not use twitter and barely use facebook, but I also dont mind if other people post my articles on there, so I have the meta tags to help with the formatting when people post a link to my articles on either of those sites.

**Comment by Jieiku** [comment]
Thanks!
