### ISSUE TITLE
Issues with Icons

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#36]
The icons I uploaded occupy their viewbox perfectly, maintaining aspect ratio. However I just realized that the "feather icons" and websites you got from have margins embedded into the SVG. Not sure by how much, but is noticeable. My icons look a tad big in comparison.

![2022-05-12_15-15](https://user-images.githubusercontent.com/48108917/168151435-55f8beaa-6ae3-42d5-a64b-18916c54201e.png)

**Comment by simbleau** [comment]
Working on this now

**Comment by simbleau** [comment]
Confirmed suspicion by opening other icons:
![2022-05-12_15-52](https://user-images.githubusercontent.com/48108917/168157174-3d2320f5-bbfa-4332-b48f-97527810f235.png)

**Comment by simbleau** [comment]
All of the icons are in a bounding box of 24x24, however have 1pt margins on all sides.

**Comment by simbleau** [comment]
Option 1: We erase the margins on all prior icons, except the 3 in question which fit their bounding box (e.g. change all other icons to `viewbox '1 1 22 22'`)

Option 2: Give our icons a new bounding box
So here's my quick napkin math:
original margins = 1pt margin/22pt icon = 1/22 = 0.045454545%
The original viewbox is '0 0 24 24', which is 'x-min y-min width height'
new margins = 0.045454545 * 24 = 1.090909091
new viewbox = `viewbox '-1.090909091 -1.090909091 26.181818182 26.181818182'`

**Comment by simbleau** [comment]
I'm going to choose option 1, since it has a smaller data footprint (less digits to encode) and is simpler to understand. This will change the viewbox on all icons except for the 3 new icons.

**Comment by Jieiku** [comment]
The 1 point marge out the outside of the icon allows for a stroke width of 2  1px inside your line and 1px outside your line. if you have the lines too close to the edge then it only works for icons that are fill without stroke.

**Comment by simbleau** [comment]
Just ran into this...
![2022-05-12_16-26](https://user-images.githubusercontent.com/48108917/168162152-05db164c-4b8f-4a72-ac19-18909bd8bb8e.png)

**Comment by Jieiku** [comment]
yep :)

**Comment by simbleau** [comment]
PR is up.

**Comment by Jieiku** [comment]
All the icons seem to be in good shape now, just post here if you still see an issue.

**Comment by simbleau** [comment]
Looks perfect to me!
