### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#39]
I find it to be a very common use-case to use FontAwesome, maybe we could make a config for it?

Something like, `fontawesome = true` which would bring the font into spec automatically, allowing for [`<i class="fa-solid fa-heart"></i>`](https://fontawesome.com/icons/heart?s=solid)

Pretty good use-case:
![2022-05-12_17-27](https://user-images.githubusercontent.com/48108917/168171145-5baa5048-d5ad-48d8-9a9c-b7a1d20fa643.png)

_(I did this in the most illegible way possible, inlining the SVGs in HTML)_

**Comment by Jieiku** [comment]
I am fine with adding FontAwesome so long as its disabled by default. I would rather pull the SVG icons that I need out of fontawesome and pull them into the _icons.scss (which I have done in the past for some icons.)

On my own blog I try to keep things minimal and dont want to load the entire FontAwesome Library for a few icons.

If you have a list of icons in Fontawesome I can grab them for you. the current icons in _icons.scss can be used like this:

```html
 <i class="svgs search"></i>

 <i class="svgs x"></i>
```

**Comment by simbleau** [comment]
Yep, that is the idea. I plan on releasing a blog soon "Blogging like a Rustacean", and my goal these weeks has been to shepherd a clear winner blogging solution for Zola which is fully featured and accessible for most.

This would just be one option to widen the accessibility - I think a majority might not care about the bundle size, even if it's great that you give it special attention.
