### ISSUE TITLE
Bug: Italic/Bold font missing

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#49]
Currently, the font in use does not bold or italicize correctly. Everything is upright font.

**Comment by Jieiku** [comment]
I recently changed it to ubuntu font, is this issue with the ubuntu font or the previous roboto font?

**Comment by simbleau** [comment]
Is the demo currently using Ubuntu? Doesn't look like Ubuntu to me.

**Comment by Jieiku** [comment]
Ah, I just updated the demo: https://jieiku.github.io/abridge-demo/overview-markdown-syntax/#tables

**Comment by simbleau** [comment]
I do not see Bold/Italic still

![2022-05-17_06-16_1](https://user-images.githubusercontent.com/48108917/168788959-ed9aab01-612e-4f0d-ad70-f626f9b94d4d.png)
![2022-05-17_06-16](https://user-images.githubusercontent.com/48108917/168788964-86083436-98f3-44be-ab91-97bb14652cfd.png)

**Comment by Jieiku** [comment]
Can you tell me is that running it local (zola serve?)

Does it happen on the demo site? https://jieiku.github.io/abridge-demo/overview-markdown-syntax/#tables

If so which browsers does it happen with? I tested with Firefox and Chrome, but my Operating system is Manjaro.

here is my chrome demo:
![2022-05-17_04-07-23](https://user-images.githubusercontent.com/106644/168797448-91038389-7dea-44d6-8435-9d90145950ff.png)

here is my firefox:
![2022-05-17_04-08-31](https://user-images.githubusercontent.com/106644/168797548-8ff64755-0786-4410-9b81-9dd6bed6b02f.png)

Hopefully we can figure it out the cause, its difficult to fix if I dont know what is causing it. I will see if I can find a Windows box to test from, 90% of my machines are Linux.

**Comment by Jieiku** [comment]
In chrome press `Ctrl + Shift + i` This will open the developer console, then hold down control and press F5 while on the markdown page, see if the font is actually loading:

![2022-05-17_04-18-22](https://user-images.githubusercontent.com/106644/168799238-91d56f07-bd11-44ca-93ae-ff59272f0297.png)

**Comment by Jieiku** [comment]
I am planning to move the demo to netlifly instead of github.

**Comment by simbleau** [comment]
I was on Ubuntu, however, from my work laptop (Windows) I can see the bold/italics.

I'm wondering if, perhaps, since I likely had Roboto installed locally already, there may have been conflict there.

**Comment by simbleau** [comment]
I believe that the issue is because of local font loading. Roboto was a font I've used heavily in the past, and I'm quite certain I had it downloaded (can't check from work).

It seems in the CSS every font is loaded by the same name, regardless of bold/italics:
https://github.com/Jieiku/abridge/blob/2dd1bf071c624197bf4fb064c52db77e521c0a6f/sass/fonts/_Roboto.scss#L14

**Comment by Jieiku** [comment]
OH, I bet your right the `local("Roboto"),`

Perfect, I will install the font locally and test this out! Awesome!

**Comment by simbleau** [comment]
This was the correct fix, it works now. :)
