### ISSUE TITLE
Review available code sublime themes

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#50]
Review available code sublime themes

They can be set by edditing config.toml:

```toml
highlight_theme = "material-dark"
```

I like the currently used material-dark but if you use google lighthouse on a page with code, there are contrast issues.

I am making a list of my favorites now.

@simbleau I would appreciate your feedback on this if you get some time to review the various themes available and pick out your favorites.

There is a full list of them here: https://github.com/getzola/zola/tree/master/sublime/themes

The idea is once I know which ones are favorites, make some small tweaks to improve contrast in a local copy of the sublime theme that I can bundle with Abridge.

**Comment by simbleau** [comment]
Will check it out soon ;P Pumping out a blog post.

**Comment by Jieiku** [comment]
No rush, I am working on my own list of favorites now.

**Comment by simbleau** [comment]
I also think the Bluelight theme has issues with contrast, when I barely edited the colors. I may have to increase contrast a little.

**Comment by Jieiku** [comment]
I find this useful: https://contrast-ratio.com/#%23cc4400-on-white

**Comment by Jieiku** [comment]
I made a new page: https://jieiku.github.io/abridge-demo/overview-code-blocks/

going to add a few more code language blocks after I eat.

**Comment by simbleau** [comment]
Went through all themes, ayu-dark and ayu-light would be best for Abridge probably. Keeps the orange theme.

**Comment by Jieiku** [comment]
The actual color is not critical as long as its a good starting point.

The background color DEFINITELY does not matter because I will be overriding it anyway.

So for the ayu-dark I can easy make an ayu-dark-blue and bundle it with abridge.

It is also important that theme looks nice across multiple langues, which is why I made the code blocks page: https://jieiku.github.io/abridge-demo/overview-code-blocks/

Going to add some more languages to the code blocks page now.

**Comment by simbleau** [comment]
Brilliant work.

**Comment by Jieiku** [comment]
Yeah I am definitely a fan of that one as well, it was on my short list of like 3 themes when I first looked at them.

**Comment by Jieiku** [comment]
That actually looks really clean, how your page background and code background are seamless.

**Comment by Jieiku** [comment]
> I would've easily chose visual-studio-dark, but it doesn't highlight things like the turbofish operator in Rust. :(

Maybe I can just add that? Will take a look.

**Comment by Jieiku** [comment]
Okay there are 10 bundled themes that all score 100 on google lighthouse (5 dark and 5 light)

https://github.com/Jieiku/abridge/tree/master/highlight_themes

This was a real pain to do, I did find a tool that helped immensely but it was still time consuming.

https://learnui.design/tools/accessible-color-generator.html

**Comment by simbleau** [comment]
I can confirm it works for me

**Comment by Jieiku** [comment]
Thanks! I closed the bug report at zola, I also updated the readme and the config.toml
