### ISSUE TITLE
ayu-dark/light-blue

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#52]
Tracking for this style

**Comment by Jieiku** [comment]
what exactly are you tracking? are you going to make another version of the theme?

**Comment by simbleau** [comment]
By all means, please! :) I have on-site interviews at Google in 2 weeks so I've been 11/10 busy studying 🥱 If you'd be so kind - Perhaps address the contrast issue in abridge-blue? The web links don't have enough contrast (you can web.dev/measure my blog if you need to see the issue)

**Comment by Jieiku** [comment]
This is finished, 100 in lighthouse for both the site theme and the code block theme.

I like this code block theme better with the blue so its now the default code block theme for abridge.
