### ISSUE TITLE
max img-width defaults to 100%

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#53]
This leads to some really stretched images.

I'd put it at 100% or the image width, whichever is smaller

**Comment by Jieiku** [comment]
This is something I have witnessed in a lot of the css frameworks that use normalize.css.

Admittedly I dont have any images on my blog yet, I will see what I can do about this today.

**Comment by Jieiku** [comment]
@simbleau how are you loading your images? These appear to be loading correctly:

https://jieiku.github.io/abridge-demo/overview-images/

Just need to know under what circumstances the issue happens so I can reproduce and resolve it.

**Comment by Jieiku** [comment]
This is something I have witnessed in a lot of the css frameworks that use normalize.css.

How are you loading your images?

What type of images are they?

These appear to be loading correctly: https://jieiku.github.io/abridge-demo/overview-images/

The svg icon which should be 525 wide is indeed stretched, so I will assume your talking about svg images?

Just need to know under what circumstances the issue happens so I can reproduce and resolve it.

**Comment by simbleau** [comment]
I've tried both HTML and with the new shortcodes, but images get stretched either way unless I specify a hardcoded img size. https://blog.imbleau.com/blogging-like-a-rustacean/#security

Source: https://github.com/simbleau/simbleau.github.io/blob/main/zola/content/blogging-like-a-rustacean/index.md#security

**Comment by Jieiku** [comment]
ahhh yes I see, so you did use the new shortcode:

`{{ img(path="./raph_security.png", alt="Raph's Observatory metrics") }}`

I bet if you wrote that like this it would not get stretched:

`![Raph's Observatory metrics](raph_security.png)`

**Comment by simbleau** [comment]
No matter what, it stretches. I tried it this way too.

![2022-05-19_18-33](https://user-images.githubusercontent.com/48108917/169415325-edd85870-e85d-4c57-ab9c-8a109a1bd7e7.png)

**Comment by Jieiku** [comment]
well now that is certainly interesting, going to clone your blog and try testing that way.

**Comment by Jieiku** [comment]
Can you please double check for me, I cloned your repo and all seems find if I do not use the img shortcode:

```md
<div align="center">

{{ img(path="./raph_security.png", alt="Raph's Observatory metrics") }}

![Raph's Observatory metrics](raph_security.png)

</div>
```

![2022-05-19_15-45-57](https://user-images.githubusercontent.com/106644/169416630-c9912d98-750a-4cf8-b77c-304ad5094f8d.png)

**Comment by Jieiku** [comment]
This may have been a cache issue, did you hold down control and press F5?

**Comment by simbleau** [comment]
Yes, I reset cache, issue persists

**Comment by Jieiku** [comment]
max-width:100% does not actually increase the size of the image, that would be the width property.

max-width only prevents the image from overflowing its bounds (like on a mobile page that is narrow.)

Here you can see that I have both visible, and that the lower image is indeed the correct dimensions of 485x300

![2022-05-19_16-07-40](https://user-images.githubusercontent.com/106644/169418571-05d888dd-094e-4b38-a55f-ba2fa28c2d36.png)

![2022-05-19_16-05-11](https://user-images.githubusercontent.com/106644/169418589-d848ca84-9b98-4e36-997a-115f2ba495c8.png)

can you set your page content to this:

```
<div align="center">

![Raph's Observatory metrics](raph_security.png)

</div>
```

Then Take another screenshot that shows me that the image has become a larger dimensions.

**Comment by Jieiku** [comment]
I think until I can fix the img shortcode I should probably remove it from zola, because that stretching is very bad indeed.

**Comment by simbleau** [comment]
Yeah, appears to be an issue with shortcodes. +1

Sorry for the false flag

**Comment by Jieiku** [comment]
Happy you got it sorted out, I removed the img shortcode for now. I ended up writing an imagehover shortcode that is able to use relative or root paths. I will porbably make a similar shortcode for regulater images as well.

**Comment by Jieiku** [comment]
@simbleau I wrote an img shortcode from scratch, no stretching, it also works with same path, relative path, or root path just like my imagehover shortcode.

You can review it here: https://jieiku.github.io/abridge-demo/overview-images/

I also added content to the Rich Content page so you can see all of that in action: https://jieiku.github.io/abridge-demo/overview-rich-content/
