### ISSUE TITLE
Can't update Abridge

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#55]
```
simbleau@pc:~/git/simbleau.github.io/zola$ zola serve
Building site...
Warning: Highlight language text not found in a-look-at-(r)age/index.md
Error: Failed to render content of /home/simbleau/git/simbleau.github.io/zola/content/blogging-like-a-rustacean/index.md
Reason: Failed to render img shortcode
Reason: Failed to render 'shortcodes/img.html'
Reason: Test call 'starting_with' failed
Reason: Tester `starting_with` was called on an undefined variable
```

**Comment by simbleau** [comment]
The shortcode I used is `{{ img(path="./raph_seo.png", alt="Raph's Lighthouse metrics") }}`

**Comment by Jieiku** [comment]
can you copy paste how your using the img shortcode

**Comment by Jieiku** [comment]
```rs
{{ img(src="ferris.svg" class="" alt="" w=600 h=400) }}
```

the old one used path=   this one uses src=  this makes it more intuitive since the html tag is

```html
<img src="">
```

what I *could* do is make it so that value could be specified as either src or path.... but im not sure if i *should*

**Comment by simbleau** [comment]
`{{ img(path="./raph_seo.png", alt="Raph's Lighthouse metrics") }}`

**Comment by Jieiku** [comment]
try:

```rs
{{ img(src="./raph_seo.png", alt="Raph's Lighthouse metrics") }}
```

**Comment by simbleau** [comment]
Re-opening because it won't render the shortcode using the slug you provided
![2022-05-23_17-27](https://user-images.githubusercontent.com/48108917/169908742-6db3af25-a05d-4c3e-8c54-6918d9bd32e5.png)

**Comment by Jieiku** [comment]
mmm interesting, one moment.

**Comment by Jieiku** [comment]
try:

```rs
{{ img(src="raph_seo.png", alt="Raph's Lighthouse metrics") }}
```

If it is what I think it is, then this will fix it, and I will add some gotcha checks to the shortcode.

Generally `./` should only be used to target a relative path such as `./imagefolder/raph_seo.png`

If this fixes it I will add some automatic corrective magic to the shortcode by searching for the presence of an additional slash and if missing then use same folder type instead of relative type.

**Comment by simbleau** [comment]
That fixed it

**Comment by Jieiku** [comment]
Cool, I will add some more handling to the shortcode so that others dont run into this.

**Comment by Jieiku** [comment]
relative paths can now be used for the same directory src="picture.svg" or src="./picture.svg"
