### ISSUE TITLE
Security Headers 'unsafe-inline' script-src and style-src

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#57]
Currently in my CSP I have `script-src 'unsafe-inline'` without this the built in search stops functioning, but [mozilla observatory](https://observatory.mozilla.org) does not like this, and neither does https://csp-evaluator.withgoogle.com

![2022-05-25_12-48-16](https://user-images.githubusercontent.com/106644/170355060-99eea4a0-e5ef-48b4-914d-7c022687a1f1.png)

**Comment by Jieiku** [comment]
![2022-05-30_02-09-32](https://user-images.githubusercontent.com/106644/170958435-c172535d-0623-442a-9735-99b09807a5d9.png)

I modified the javascript search results page so that it is no longer in-lined. This allowed me to remove unsafe-inline from the script src CSP. I also found out you can set headers for netlify. The headers can be set a couple different ways, but I went with the simple toml method: https://github.com/Jieiku/abridge/blob/master/netlify.toml

I can even get another 10 points if I remove unsafe-inline from style, but that would break the imghover shortcode that I wrote.

I asked for help/ideas on how I could get the shortcode to output some of its code into the <head> (the <style> portion)

https://zola.discourse.group/t/advanced-usage-shortcodes-inject-style-into-head/1330

I am still brainstorming, but what I am trying to do with that shortcode may not currently be possible without extending Zola with a new feature.

**Comment by simbleau** [comment]
This is a powerful motivation to use Netlify.

**Comment by Jieiku** [comment]
It can be configured to auto build on commit, its just as slick as github pages: https://www.getzola.org/documentation/deployment/netlify/

**Comment by simbleau** [comment]
I think what this project would benefit from (generally, or eventually) would be a migration guide. How to:
- Set it up an Abridge blog from scratch
- How to migrate from common hosting like GitHub Pages and GitLab Pages.
- How to change from another theme

**Comment by Jieiku** [comment]
The next thing to do will be to implement class based code block styles, they currently require unsafe-inline when you use the .tmTheme file. These files can however be converted to work with the class method.

https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting

Will play around with that tomorrow. I pushed a lot of SEO fixes and documentation yesterday as well.

**Comment by Jieiku** [comment]
99% of this has been addressed all that is left is style-src that is used for imghover shortcode.

going to close this and open a new more relevant issue.
