### ISSUE TITLE
logo config

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#59]
2 things

1) Logo icon should be vertically centered when it exists.
`logo = { file="logo.svg", width="5", height="5", alt="Abridge", text="bridge" }`

2) Eliminate `textlogo = 'Abridge'` in favor of
`logo = { text="Abridge" }`

**Comment by Jieiku** [comment]
I have changed it to this:
```toml
#uncomment one of the two lines, or neither, depending on which type of logo you want to use:
logo = { file="logo.svg", width="32", height="32", alt="Abridge", text="bridge" }
#textlogo = '<font color="#f90">A</font>bridge'
```

textlogo is meant to be a config options for anyone that wants to use a purely text based logo, so you could comment out logo and define only textlogo, I did go ahead and comment out textlogo by default and add a note.

when I set width and height to 5 the logo got super tiny, almost invisible, I set it to 32 (down from 42) which looks good to me:
![2022-05-26_09-29-06](https://user-images.githubusercontent.com/106644/170531979-26c79cb6-0105-47ea-9ac0-138c6c23b7bd.png)

**Comment by Jieiku** [comment]
Actually when the page is collapsed narrow it could use a touch of margin at the top, will address that now.

**Comment by Jieiku** [comment]
and now here it is in a narrow window:

![2022-05-26_09-39-07](https://user-images.githubusercontent.com/106644/170533717-3dc53744-1aec-4a64-b218-549cc7d45382.png)

**Comment by Jieiku** [comment]
and now here it is in a narrow window:

![2022-05-26_09-44-45](https://user-images.githubusercontent.com/106644/170534721-9cc9c12f-8517-4038-af37-66cb854341f5.png)
