### ISSUE TITLE
add option to customize accent color / hover color for links

### ISSUE THREAD

**Issue by craftyguy** [Jieiku/abridge#6]
The default orange is nice, but it would be cool to have an option for customizing this. Looks like it's set in `sass/themes/_auto.scss`, however I'm not sure what the best way would be to expose this to an option in config.toml...

**Comment by craftyguy** [comment]
hmmm this might not be possible because of a design "flaw" with zola...

https://zola.discourse.group/t/overriding-sass-in-tempate/175

**Comment by Jieiku** [comment]
Yes you are correct, I think so long as people know where to edit this color that it will not be a problem. generating a new css file from the sass files is handled automatically by zola, so they only need to update the color in the sass files and rebuild. I will add a note about this to the readme now.

**Comment by Jieiku** [comment]
I added a ntoe to the readme: https://github.com/Jieiku/abridge/commit/a7ac9d5ce95410262a3e76ab7dc14847e0d4292d

**Comment by Jieiku** [comment]
Just wanted to post that This theme now allows configuring which css file to load.

@simbleau created their own theme, which they can load in their config.toml file.

https://github.com/Jieiku/abridge/blob/master/sass/abridge-bluelight.scss
https://github.com/Jieiku/abridge/blob/master/sass/themes/_bluelight.scss

**Comment by craftyguy** [comment]
that's awesome, thanks for pointing that out!

**Comment by simbleau** [comment]
I guess I'll plug the preview - https://spencer.imbleau.com/blog uses this theme.

**Comment by craftyguy** [comment]
interesting, it seems like that site isn't showing a dark version of the site even though I have my browser configured to prefer dark themes. maybe their custom theme doesn't include a dark version?

**Comment by simbleau** [comment]
Bluelight has no dark version, but that is a current PR #43
