### ISSUE TITLE
Static asset cache policy

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#64]
Not sure if you get this too, but I thought I'd flag it
![2022-05-29_07-37](https://user-images.githubusercontent.com/48108917/170865989-2d787847-7267-41a5-93bd-6d83a3c3fd92.png)
.

**Comment by Jieiku** [comment]
I *was* getting this. This issue has to do with the web server. In Apache or Nginx you can set the cache TTL. Once I moved the demo to netlify I no longer have this issue.

**Comment by simbleau** [comment]
So would this be an impossible fix for GitHub Pages?

**Comment by Jieiku** [comment]
yep, afraid so.
