### ISSUE TITLE
Remove any and all occurances of onload="" this is considered an unsafe-inline script

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#66]
Remove any and all occurances of onload="" this is considered an unsafe-inline script.

This was first introduced here: https://github.com/Jieiku/abridge/commit/f454701378ec80345bafa460d0ac9fc6f9d27f56

and I have since used it for a couple other resources.

The proper way to do this while still allowing for a secure CSP not allowing unsafe-inline. is to instead set an id on the element. Then have a javascript file that loads and processes any elements with a given id  eg:  id="preloadStyle" and change those with that id to rel="stylesheet" on page load.

**Comment by Jieiku** [comment]
This is now resolved. Will be part of the big update I will be committing soon.

**Comment by simbleau** [comment]
Ah looking forward to it. About to have my Google interviews which attributes my lack of activity recently. Lots of studying.

**Comment by Jieiku** [comment]
Good luck!

**Comment by Jieiku** [comment]
This is now completed.
