### ISSUE TITLE
Double Search Icons, top menu centering

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#68]
_Originally posted by @simbleau in https://github.com/Jieiku/abridge/issues/10#issuecomment-1151476914_

Looks awesome! 

Only 2 minor things
- header links aren't centered
- search box has 2 search icons

![image](https://user-images.githubusercontent.com/48108917/172921123-27532d6e-74a7-4988-833c-3128fc993ed0.png)

_Originally posted by @simbleau in https://github.com/Jieiku/abridge/issues/10#issuecomment-1151476914_

**Comment by Jieiku** [comment]
@simbleau you will have to let me know how you got that image that shows the double search icons.

Was that from a desktop browser in a special mode? Was it from and android emulator? Was it from an actual phone, and if so what version of android, and what display resolution?

**Comment by simbleau** [comment]
It is from Safari on my iPhone 13... hmm

**Comment by Jieiku** [comment]
I might have an idea for this, but I will need you to test it, I dont own an iphone. I am not sure if I will get to it today or not, got some errands to run.

**Comment by Jieiku** [comment]
I changed the form input box for the search from type="search" to type="text" and I believe this should fix it.

Let me know how it looks on your phone now.

**Comment by simbleau** [comment]
Bingo

![image](https://user-images.githubusercontent.com/48108917/173033219-dc8ac0d2-c4c9-42cd-a31a-c7bdf9023e4c.png)
