### ISSUE TITLE
Shortcodes img(src) should be path

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#69]
In the overview with images, it gives improper instructions saying to use img(src=...

Should be path

**Comment by Jieiku** [comment]
I am not sure I understand, your talking about [this page?](https://abridge.netlify.app/overview-images/)

here is the source code for that page, you can see that I am using img src not img path, and that the page renders the images properly.

https://raw.githubusercontent.com/Jieiku/abridge/master/content/overview-images/index.md

Maybe you have an old version of the short code? here is what it currently looks like:

https://github.com/Jieiku/abridge/blob/master/templates/shortcodes/img.html

Let me know what you figure out, I don't see any issues.

**Comment by simbleau** [comment]
Yeah might just be having issues merging in all your new changes... standby

**Comment by Jieiku** [comment]
If you have to you can rebase it:

cd abridge
git reset --hard 2ef7c0ec1ff976b807691fea23eaaf5ea1e93bc9
git pull

**Comment by simbleau** [comment]
Yeah, honestly, whatever I do I can't get it to work. 

I did that and tried removing the shortcodes. Now it complains about a macro::resource and get_path not functioning. Then I saw "pages.html" and every other template not being found. At this point... not sure.

By any chance would you mind seeing if you could fork my repo, pull your changes from Abridge and see if it functions for you? I'm having no luck and the Zola error messages are not very helpful to me. If you do get it working, please give me a PR. Would be super helpful!

**Comment by Jieiku** [comment]
sure, not a problem.

**Comment by Jieiku** [comment]
Pull Request is there: https://github.com/simbleau/simbleau.github.io/pull/11

After removing and adding the Abridge module, I only needed to update the config. toml, there was a very large number of changes.

I also made a safari-pinned-tab.svg for you.

**Comment by simbleau** [comment]
Thank you so much! Not sure what went wrong. I merged it, but I am now seeing this, notice the font change on the date. Any clue why?
![2022-06-10_18-40](https://user-images.githubusercontent.com/48108917/173159625-96236ae2-b755-4c6a-87c6-6279b6860c94.png)

**Comment by simbleau** [comment]
I'll be honest it's quite jarring. It might be the same font, but it definitely looks off, at least the spacing.

**Comment by simbleau** [comment]
Also is there any chance we could see the "Day/night" switcher turn colors too? It is the only grey item on my site and sticks out a bit unnaturally... Which isn't too big of a deal.

**Comment by Jieiku** [comment]
ahh ok, I can try some stuff, but it would be helpful if you could try some values as well, let me find the values that change those settings and post them here, one moment.

**Comment by simbleau** [comment]
Sure thing.

**Comment by simbleau** [comment]
We can scratch needing the day/night icons switching colors - I just noticed you uploaded a better blue theme which uses grey. I like it more! No action necessary.

**Comment by Jieiku** [comment]
One file which adds a little space between them so they are not crammed together is sass/include/_zola.scss

You will see a class .rpad that adds a little right padding to each of those elements.

In this Same file you will see a .info  this is what makes the font-size of everything down there smaller.

Play around with these and see what you like.

**Comment by simbleau** [comment]
The main things:
- "May 17, 2022" vs "2022 May 17"
- "9 min read" could probably be on the same line as the title
- The metadata was moved to the bottom of each post, which I'd rather see as close to the title as possible

**Comment by Jieiku** [comment]
for the position of the info we can have an option in config.toml

I can set the date format back to month day, year

let me make a couple changes in a few minutes and see how you like it.

**Comment by simbleau** [comment]
![2022-06-10_19-06](https://user-images.githubusercontent.com/48108917/173161064-b3b426b1-11b6-4b98-9944-b3ebd3db91e1.png)

**Comment by Jieiku** [comment]
looks good, but on longer titles the appears of the read time may end up looking odd... like when it needs to wrap. especially if it ends up wrapping only the read time.

I can definitely make an option to have the readtime on the title if thats how you want it though!

**Comment by simbleau** [comment]
The bottom font size was 1em, same as the rest of the font

**Comment by simbleau** [comment]
I don't like it being on the same line honestly, I've tried making it look better lol, thoughts?
![2022-06-10_19-06](https://user-images.githubusercontent.com/48108917/173161475-6ce71517-6df2-44d1-8d55-21a1c4853ff0.png)
.

**Comment by Jieiku** [comment]
So you thinking keep the read time with the other metadata?

**Comment by simbleau** [comment]
Yes

**Comment by Jieiku** [comment]
yeah, thats why I removed the author on the index, I am thinking What I want to do is make an option

author_page and author_index, so that I can display the author on the article, but not on the index.

**Comment by simbleau** [comment]
![2022-06-10_19-19](https://user-images.githubusercontent.com/48108917/173161819-e574ace9-aefd-4caa-b7c0-0c63e2545a66.png)
I wouldn't care if fontawesome was leveraged here

**Comment by simbleau** [comment]
This would be my favorite:
![2022-06-10_19-22](https://user-images.githubusercontent.com/48108917/173161939-98a24ebb-4992-4f43-b4ca-3c75ceb455b0.png)

**Comment by Jieiku** [comment]
what does the code like that look like, paste it here, and I will work it into some options for the config.toml

**Comment by simbleau** [comment]
The changes nessary to do this are simple:
- Change the font size back to 1em for the info class.
- rpad only on the glasses and calendar items.
- glasses: `<i class="fa-solid fa-glasses"></i>`, calendar: `<i class="fa-solid fa-calendar"></i>`, info: `<i class="fa-solid fa-circle-info"></i>`

**Comment by Jieiku** [comment]
ahhh i see you put the category closer to the tags, i like that too.

**Comment by simbleau** [comment]
> ahhh i see you put the category closer to the tags, i like that too.
> 
> I will add some class options for those meta fields, then people can set whatever class they want, which would support custom svg css or fontawesome.

If they opt into fontawesome, we already define a different search icon. We should do the same here

**Comment by Jieiku** [comment]
yeah, I will make the class definitions for these the way you set  it, so that if they enable fontawesome then they are good to go. (so long as they started with the example config.toml)

**Comment by Jieiku** [comment]
I completed most of this, also I think I probably can apply color to that svg search icon dynamically, going to give a try anyway.

**Comment by Jieiku** [comment]
give that a try, don't forget the new options in config.toml

**Comment by simbleau** [comment]
Awesome work! Currently it's missing some padding around the icon:
![2022-06-11_12-28](https://user-images.githubusercontent.com/48108917/173196514-528671f6-0188-4326-a2ec-6b3425c577a9.png)

**Comment by simbleau** [comment]
Also a (very) minor thing I noticed was the light/dark icon appears cut off on the right side:
![2022-06-11_12-29](https://user-images.githubusercontent.com/48108917/173196539-03b6bf8c-1196-464a-992e-97be9dfe0556.png)

**Comment by Jieiku** [comment]
Interesting you spotted that, I also noticed the same thing on the very top of the fontawesome spyglass in your search.

It seems to be something that affects the fontawesome icons but not the ones included with abridge.

**Comment by Jieiku** [comment]
I will fix that icon padding now, just need to add a space.

**Comment by Jieiku** [comment]
I think I might know the solution for the clipping on the fontawesome icons, probably set the height but not the width with a new class similar to svgs
