### ISSUE TITLE
Migration from subdomain to slug URL

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#70]
So, I have some long term plans.

Firstly,
my portfolio site is hosted at https://spencer.imbleau.com

I'd love if I could host my blog at https://spencer.imbleau.com/blog (with that as the base_url in config) and somehow get that to work. Previously I had it working on blog.imbleau.com

I'm running into some big friction. Right now my nginx proxy server just proxies https://spencer.imbleau.com/blog as https://simbleau.github.io/blog, which seems to kindof work, however, it breaks all non CORS javascript, seems to break images, and all links point to the GitHub.io site. Just doesn't seem to be clean, but it's very possible I'm doing several things wrong.

I'll leave my site broken for a few hours so you can hopefully see it.

I'm unfamiliar with netlify but if there's genuinely anyway to make this work -at all- and be streamlined, I will happily take it. 

I had it worked fantasticly as blog.imbleau.com since it just required a CNAME file in the static/ and a redirect from spencer.imbleau.com/blog -> blog.imbleau.com, but I just found that to be not fun! Is there anyway you know I can do this with either GitHub Pages or Netlify?

**Comment by Jieiku** [comment]
I have not tried using a domain name with Netlify yet, but I have a spare domain name that I could test this with. Prior to working on Abridge I never used netlify for anything. (Most of my projects are self hosted from home so I have complete control over everything.)

I am looking at your site now, give me a minute to take some notes.

**Comment by Jieiku** [comment]
not sure about fontawesome yet though.....

**Comment by Jieiku** [comment]
you can see not all your images are broken, look here: https://simbleau.github.io/blog/blogging-like-a-rustacean/

**Comment by simbleau** [comment]
Well yes, that's because you clicked a link and it went to the github.io version

https://spencer.imbleau.com/blog/blogging-like-a-rustacean/ 

Images are broken

**Comment by Jieiku** [comment]
ahhhh ok one sec

**Comment by simbleau** [comment]
I thought the demo was originally hosted on a slug URL, but perhaps I was wrong... Maybe this is my issue to figure out :P

**Comment by Jieiku** [comment]
I see the problem.

**Comment by simbleau** [comment]
Ah, I see what you did, but that implies I have to host it. I'll tinker as best I can. but I want to use GitHub pages to host, and use my domain as a masking alias. I don't want to use one of my servers to actually host it.

When I said I use nginx, I don't serve through nginx, my nginx server is acting purely as a reverse proxy server.

**Comment by Jieiku** [comment]
so when somebody hits spencer.imbleau.com

it goes where? I see a couple different IP addresses when I use dig spencer.imbleau.com

the term reverse proxy is not foreign to me, I have used both nginx and haproxy as reverse proxies before, but I want to make sure I understand all the hops, for example here is one scenario I use.

jieiku.example.com  >  cloudflare-registrar  >  IP address of my HAProxy server  > HAProxy SSL offloading >  Local container behind firewall

**Comment by simbleau** [comment]
*.imbleau.com -> cloudfare -> nginx reverse proxy server -> simbleau.github.io

**Comment by simbleau** [comment]
My gut feeling is that this may not be possible to do without hosting it myself.

At the least, I think it would require all of the links to be re-written to be relative, so one wouldn't get booted to the canonical address in a proxy situation like I have.
