### ISSUE TITLE
Pagination Spacing and tap target size

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#73]
![2022-06-20_08-57](https://user-images.githubusercontent.com/48108917/174606836-5c9ae9eb-9c56-4cf0-a23c-256d23c64c7c.png)

The spacing seems... off

Gives -1 on SEO because the icons are not at least 48x48, as well.

**Comment by Jieiku** [comment]
Should be fixed, feel free to post here if you still see issues after updating submodule and adding the latest config.toml changes.
