### ISSUE TITLE
Console errors for fonts/roboto

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#74]
Any clue why I'm getting web.dev which finds console log errors?
On my web browser I get no console logs, so I have no clue what's going on. I also don't load Roboto.

![2022-06-20_09-22](https://user-images.githubusercontent.com/48108917/174611366-2cd6abb8-5eb4-43e0-a6e7-cf843a728ffc.png)

**Comment by Jieiku** [comment]
Should be fixed, feel free to post here if you still see issues after updating submodule and adding the latest config.toml changes.
