### ISSUE TITLE
Cumulative layout shift with Fontawesome

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#75]
It seems like fontawesome adds some decent layout shift. I'm wondering if - perhaps - we could assume the size of every fontawesome icon is 1em tall/wide (16x16) to reduce shift.

![2022-06-20_09-26](https://user-images.githubusercontent.com/48108917/174611868-e85c0a13-02d9-4f53-97fe-ad48178a566d.png)

![2022-06-20_09-24](https://user-images.githubusercontent.com/48108917/174611549-ea2dda64-0041-4dd2-a3f9-8e4951589346.png)

**Comment by Jieiku** [comment]
Should be fixed, feel free to post here if you still see issues after updating submodule and adding the latest config.toml changes.

**Comment by Jieiku** [comment]
This is not only an issue with fontawesome, it seems to also be an issue with a recent change that only affects chrome, not firefox, so I missed it. Taking a look at it now.

**Comment by Jieiku** [comment]
I did some more work on spacing and sizing of elements.
