### ISSUE TITLE
More fontawesome icons

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#76]
For the pagination and caret-up to return to the top, 

![2022-06-20_09-27_1](https://user-images.githubusercontent.com/48108917/174612129-d62a5758-02cd-4ee6-9f8b-cf721ec1f4c5.png)
![2022-06-20_09-27](https://user-images.githubusercontent.com/48108917/174612132-721e60e1-8dfc-4397-8d42-c74c6abe1c5b.png)

I'm hoping if we already use fontawesome we could use the following icons:

![2022-06-20_09-29](https://user-images.githubusercontent.com/48108917/174612455-c9f78561-80cd-434a-acc1-791dc7e902a0.png)

My preference would be to use `circle-caret-up` to return to the top,
and use `angles-left`, `angle-left`, `angle-right`, and `angles-right` for the pagination.

**Comment by Jieiku** [comment]
Should be fixed, feel free to post here if you still see issues after updating submodule and adding the latest config.toml changes.
