### ISSUE TITLE
Separate Day/Night Icons

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#78]
I thought this would be a cool suggestion, not necessary to implement.

But I was looking for some nice day/night icons when you implemented the last commit.

It would be nice if we could use two icons, one to "turn the lights on" and one to "turn the lights off". Those wanting the current static icon can simply set both to the same icon.
![2022-06-22_06-49](https://user-images.githubusercontent.com/48108917/175012095-6389d58a-5634-46f2-a61f-179f84fd1d20.png)
![2022-06-22_06-53](https://user-images.githubusercontent.com/48108917/175012205-2fd7c1d8-df19-46ee-b75e-b3560c8c4b74.png)
![2022-06-22_06-53_1](https://user-images.githubusercontent.com/48108917/175012211-c6c18729-1316-4f0e-b1a6-ef362da1b7a3.png)

**Comment by Jieiku** [comment]
I would accept a pull request for this, but I would want the icon switching done in a separate js file so that users using the static icon don't unnecessarily have more JavaScript.

(I can add another bundle option for it.)

**Comment by simbleau** [comment]
I've been experimenting with WASM a little hoping to learn how to tackle this one. Give me a week and I'll probably have a PR. :)

**Comment by Jieiku** [comment]
yeah, wasm is great. I just dont want to load extra js or wasm for users that are using the static icon, but we should be able to add a new bundle and load it only for the users that want the icon to switch, so I don't think it should be a problem.

I experimented with different icons, and in the end I decided for my site that the static icon keeps things nice and simple.

**Comment by Jieiku** [comment]
I don't want to deter you from learning WASM, but it seems for such a simple function that the javascript will actually be significantly faster/lighter. I just read over this today: https://javascript.plainenglish.io/webassembly-vs-javascript-can-wasm-beat-javascript-in-benchmark-cd7c30faaf7a

**Comment by simbleau** [comment]
Ah, I knew this, however, it didn't really bother me.

Well, there's really 2 reasons it doesn't bother me.

1) WASM *will* be better in time. As of the present, using DOM APIs from WebAssembly is still slower than calling them directly from JavaScript. This is a temporary issue which the [WebAssembly Interface Types](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) proposal aims to resolve. If you would like to learn more, check out this [excellent article](https://hacks.mozilla.org/2019/08/webassembly-interface-types/) (from Mozilla) which describes the proposal.

2) Good design requires compromise, and the good design is WASM everywhere in Abridge. Since JS is currently faster by the stroke of DOM API calls, it's a particularly niche situation when you either 1) have so much functional indirection it's slower than WASM (unlikely), *or* 2) the Javascript is extremely simple (which would be this case). In the 2nd case at least, I don't think there's a strong enough argument to keep JS on the tech stack in a sea of WASM. The performance gain would be sub-milliseconds.

**Comment by Jieiku** [comment]
if the performance difference is really sub-milliseconds then it don't matter to me at all, checking out that article you linked now.

**Comment by simbleau** [comment]
I'll retract "would be" sub-milliseconds for *probably would be*. Lots of variables there.

But since this is a temporary problem, I'm going to keep prodding on, even if we don't merge it in.

Also I would lower the bar to 16ms of allowable indirection, based on 60fps, a common standard.

**Comment by Jieiku** [comment]
I am really interested in seeing what you come up with, it sounds very interesting, I am interested in most things rust.

**Comment by simbleau** [comment]
I forgot a decent 3rd reason: For those who disable Javascript on their browser (all 3 of them on Earth), Abridge would still work.

I won't claim good results yet. I started to look into WASM early this week from 0 experience. I am not a front-end dev. But I found exactly what I needed from [this Mozilla article](https://hacks.mozilla.org/2018/04/javascript-to-rust-and-back-again-a-wasm-bindgen-tale/).

Unfortunately I've been nerdsniped by Yew. It's been fun because I'm not a frontend dev at all (clearly), and I found the system really interesting, with props, components, and other features similar to Vue/React. Also found a CSS macro library for it called stylist-rs.
![2022-06-26_20-09](https://user-images.githubusercontent.com/48108917/175839454-4b67582c-1fed-48f5-8632-838337343a8b.png)

**Comment by Jieiku** [comment]
I looked at Yew quite a bit for another more dynamic project I am working on, I ended up going with Actix mostly because of maturity and I found a really good starter template that uses PostgreSQL which I also like:  https://github.com/secretkeysio/jelly-actix-web-starter

**Comment by Jieiku** [comment]
that 3rd reason is a very compelling reason, cant wait to see what you come up with even more now!

**Comment by simbleau** [comment]
Isn't Actix a backend framework, like Rocket?

Yew is a frontend framework in Rust. :)

**Comment by Jieiku** [comment]
Well, the Jelly actix starter is a backend yes, but it uses tera templates to render the html (just like Zola!), so you literally just serve it up like most html, I have nginx sitting in front of Jelly Actix starter

**Comment by simbleau** [comment]
Ahh. That sounds fun.

I also did [some fun](https://github.com/simbleau/website#-gitops). I have a CI/CD pipeline which uses GitHub Actions to build the WASM website with aggressive size compression - then builds a new Docker image using the packed `dist/` folder and lays an nginx server on it.

My kubernetes cluster at home detects the docker image when it updates and automatically rebuilds to the latest tag with FluxCD.

A verrrry different approach, because I focused on site reliability, but worth mentioning, since I like my solution.

**Comment by Jieiku** [comment]
ah, apparently you can use Yew with Actix or Rocket. (When you need something VERY dynamic.) Things that come to mind are things like a web music player etc.

**Comment by simbleau** [comment]
Just finished the theme switch WASM piece and demo. Just a few minutes to upload...

**Comment by Jieiku** [comment]
Awesome, will check it out in a bit, have a good night.

**Comment by simbleau** [comment]
Progress update: Just got finished a theme switcher for [my website in progress](https://github.com/simbleau/website/). 

It now is exactly how the abridge switcher works in complete WASM:
- On page load, query local storage for your theme choice. If there is no theme choice in local storage, it performs a media query to check your browser's preference
- Changing themes will save a theme choice into local storage

I'm really happy with the results and I've learned a lot. We will start to see more experiments in abridge-wasm and probably the first pull request into abridge to introduce WASM.

![2022-07-03_14-34](https://user-images.githubusercontent.com/48108917/177053256-53879abb-e3ec-43e1-855f-3f8be681b3f1.png)
![2022-07-03_14-34_1](https://user-images.githubusercontent.com/48108917/177053263-31dc356c-24e8-490a-ae9d-7b0a063817a0.png)

**Comment by Jieiku** [comment]
Awesome! Happy 4th of July!

**Comment by Jieiku** [comment]
Closing for now (stale). Not opposed to an icon switcher so long as it is not the new default. I like the static icon as the default.
