### ISSUE TITLE
Code block header

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#80]
I just noticed that the dark theme has a slightly constrasting background color while the light theme does not for code blocks. I don't care if it's the same or slightly different, but I'd hope they are consistent.
![2022-06-24_07-36](https://user-images.githubusercontent.com/48108917/175527028-0f6c67c0-2866-4d46-981e-d8c461e09eb8.png)
![2022-06-24_07-35](https://user-images.githubusercontent.com/48108917/175527032-8c9f7068-2dc9-441a-9531-699da3bb3e80.png)

Also not sure how much I like code type (`rs:`) on the code block itself, which I also noticed blends in too well with the `use` statements on the next line, especially on light theme.

I think it would be nice if we could aim for something pleasant with rounded borders and a clear heading line, although I'm not sure how feasible it is:

![2022-06-24_07-54](https://user-images.githubusercontent.com/48108917/175529291-f55f2636-09b3-4977-b7c5-51e0e403490e.png)

**Comment by Jieiku** [comment]
Yeah I plan to work on this eventually, I will be a bit busy for a while. The idea for the current implementation on the code block naming comes from here: https://github.com/getzola/zola/issues/1851

I think the copy button used looks good, but agree that the code block name could be better

**Comment by simbleau** [comment]
Rockstar. :)

**Comment by Jieiku** [comment]
I addressed most of this, there is a limit to how much you can do with the ::before operator, most styles cannot be applied to it.

I enclosed the tag in brackets instead of a following colon, I also capitalized it all and put an extra line break, I think this gives plenty of separation and makes it apparent that it is a title/tag and not part of the code.

**Comment by Jieiku** [comment]
I got a lot of this worked out in the refactor branch, the Tabi theme recently implemented some changes that format it close to what you were looking for, here is the result:

![2023-07-17_15-29-19](https://github.com/Jieiku/abridge/assets/106644/e04cb644-7495-4f4f-be79-efab4078c242)

Just waiting for the next version/subversion of zola to relase before I merge the refactor branch of abridge.
