### ISSUE TITLE
Add obfuscation for email addresses.

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#83]
Add obfuscation for email addresses.

Found this blog that popped up recently: https://fgage.com/ and seen a js script loaded that I did not recognize: `email-decode.min.js`

Apparently most bots that scrape pages for email address do not bother to load the javascript of the page, so this helps eliminate some of the spam.

https://andrewlock.net/simple-obfuscation-of-email-addresses-using-javascript/

After I implement and test this I will add it to the bundle, it looks like a fairly light script.

**Comment by simbleau** [comment]
Hot damn that's massive. I've always wondered why I get so many spam e-mails.

**Comment by simbleau** [comment]
A thought came across today... Anything loaded with WASM would not be in the source by default. If you look at my [home page](https://spencer.imbleau.com), it is loaded with WASM and the source will tell you nothing. WASM inherently happens to be a great form of source obfuscation.

**Comment by Jieiku** [comment]
very true, I think in either case they would need to use an actual web browser to scrape the mailto link, not necessarily from the source but from the dom, right click inspect instead of view source.

The javascript solution likely would not show the real email address in the source either, but both solutions would probably show the actual email address in the DOM.

I have been crazy crazy busy the last few days, and will probably be busy for a few more days, but once I get caught up on some stuff I will implement this and do some testing.

**Comment by simbleau** [comment]
Nice stuff.  :)

**Comment by Jieiku** [comment]
This is completed, works properly. Did not use any key based encryption. I simply use bas64 encode and some simple string manipulation, likely this is sufficient because the decode key was part of the string used in the other example.
