### ISSUE TITLE
Hide "About" when marked as Draft

### ISSUE THREAD

**Issue by ms-ati** [Jieiku/abridge#92]
Hi @Jieiku, thank you again for this amazing theme! Is it possible to change the logic in the templates, so that when About or another Page is marked as Draft, then it will not be rendered in the navigation menu?

Thank you!

**Comment by Jieiku** [comment]
Yes, I think this should be easy enough to add. Will try to add this feature today.

**Comment by Jieiku** [comment]
This is trickier than I thought it would be, there are some ways of doing this such as changing this:

```
menu = [
    {url = "/about/", name = "About", slash = true, blank = false},
    {url = "/posts/", name = "Posts", slash = true, blank = false},
    {url = "/categories/", name = "Categories", slash = true, blank = false},
    {url = "/tags/", name = "Tags", slash = true, blank = false},
]
```

to this:

```
menu = [
    {url = "/about/", name = "About", slash = true, blank = false, draft = true},
    {url = "/posts/", name = "Posts", slash = true, blank = false, draft = false},
    {url = "/categories/", name = "Categories", slash = true, blank = false, draft = false},
    {url = "/tags/", name = "Tags", slash = true, blank = false, draft = false},
]
```

This would however have the affect of having to set draft status both in the page and in the config.toml for the menus. This solution would be simple to implement but is not as convenient when it comes to managing a site/blog.

I am reviewing the tera/zola documentation for a good way of doing this.

**Comment by ms-ati** [comment]
Cool cool -- as a workaround, for anyone else reading this, it's just as easy to simply comment out the `{url = "/about/", name = "About", slash = true, blank = false},` lines in `config.toml` for the time being while working on a draft About page -- but excited to see if you come up with a dynamic way!
