### ISSUE TITLE
Multilingual search

### ISSUE THREAD

**Issue by gumbrecht** [Jieiku/abridge#95]
Hello,

the documentation does not mention how to customize the search. By default search points to https://abridge.netlify.app/. It seems to me that the `search_bundle.min.js` needs to be adjusted. But how it this done properly?

**Comment by Jieiku** [comment]
You have to configure the site using the config.toml

`base_url = "https://abridge.netlify.app"`

**Comment by gumbrecht** [comment]
I have already configured my (multilingual) website with your nice theme.  Everything is ready except the search…

In order to run `npm run abridge` there needs to be installed the package `abridge` — is it [this abridge package](https://www.npmjs.com/package/abridge)? This confuses me a bit as this package is 10 years old…

Please bear with me as I am not a programmer and thank you for your help.

**Comment by Jieiku** [comment]
`npm run abridge` should be ran from the abridge zola theme directory, the reason for this is because that is where the package.json file is which defines the abridge script:

If you inspect the package.json file you will see under `"scripts": {` all of the defined npm scripts:

https://github.com/Jieiku/abridge/blob/master/package.json

so for example:

```
git clone https://github.com/Jieiku/abridge
cd abridge
zola build
npm run abridge
zola build
```

**Comment by Jieiku** [comment]
I am uncertain as to why it would not work with multilingual, I can try to reproduce the issue locally and help resolve it, but it may take me a few days, I am currently fighting a cold.

**Comment by gumbrecht** [comment]
Alright, I successfully ran `npm run abridge` and `search_facade.js` was generated. The search works fine now but as mentioned only for the default language.

I will try to find out how to configure a multilingual search. If find anything I will let you know. Get well soon!

**Comment by Jieiku** [comment]
I added this to my todo list for the Refactor.

**Comment by Jieiku** [comment]
Also it appears if your other language is Chinese or Japanese that you have to build Zola to support indexing those: https://www.getzola.org/documentation/content/multilingual/
